export const TranslateCN = {
    test: 'abc{{value}}',
    LANG: '中文',
    COMMON: {
        PROMPT: '提示',
        CONFIRM: '确认',
        CANCEL: '取消',
        EXIT: '退出',
        DELETE: '删除',
        RESET: '重置',
        NUMBER: '编号',
        ORDER_NUMBER: '订单号',
        ORDER_ID: '订单ID',
        OPERATION: '操作',
        MORE_ACTIONS: '更多操作',
        STATUS: '状态',
        TYPE: '类型',
        DESCRIPTION: '描述',
        ORDERS: '订单',
        ORDER: '订购',
        OVERVIEW: '概览',
        LABEL: '标签',
        EXPENSE: '费用',
        ONE_TIME_COSTS: '一次性费用',
        TOTAL_COST: '费用总计',
        BILLING_MODE: '计费模式',
        BY_VOLUMN: '按量',
        DETAILS: '详情',
        BUY_NOW: '立即购买',
        SHOPPING_CART: '购物车',
        PURCHASE_AMOUNT: '购买量',
        PURCHASE_DURATION: '购买时长',
        ADD_TO_SHOPPING_CART: '加入购物车',
        CHECK_SHOPPING_CART: '查看购物车',
        EMPTY_SHOPPING_CART: '清空购物车',
        NAME: '名称',
        NONE: '无',
        ALL: '所有',
        DEPARTMENT: '部门',
        PURCHASER: '订购人',
        PRODUCT: '产品',
        PURCHASED: '已购',
        QUANTITY: '数量',
        PRICE: '价格',
        PERMANENCE: '永久',
        MANAGEMENT: '管理',
        INFORMATION: '信息',
        BASIC: '基本',
        ENTERPRISE: '企业',
        DATE: '日期',
        HISTORY: '历史',
        EXPLAIN: '说明',
        USERS: '用户',
        WARNING: '警告',
        PLEASE_WAIT: '请等待',

        //单位
        $: "￥",
        YUAN: '元',
        GB: 'GB',
        ONE_SET: '1台',
        TWO_SET: '2台',
        THREE_SET: '3台',
        FOUR_SET: '4台',
        FIVE_SET: '5台',

        //状态名词
        ENABLED: '已启用',
        NOT_ENABLED: '未启用',
        NOT_APPROVED: '未审批',
        APPROVED: '已审批',
        NEWLY_CREATED: '新创建',
        IN_PROCESS: '处理中',
        COMPLETED: '已完成',
        UNSUBSCRIBE: '退订',
        RENEW: '续订',
        RENEW_DATA_FAILED: '续订失败',
        START: '启动',
        SHUTDOWN: '关机',
        PAUSE: '暂停',
        RESTORE: '恢复',
        HARD_REBOOT: '硬重启',
        SOFT_RESTART: '软重启',

        //专业术语
        MIRROR: '镜像',
        CLOUD_HOSTING: '云主机',
        CLOUD_HOST_NAME: '云主机名称',
        CLOUD_HARD_DISK: '云硬盘',
        CLOUD_HRAD_DISK_NAME: '云硬盘名称',
        ENTER_CLOUD_HARD_DISK_INFORMATION_TO_SEARCH: '输入云硬盘信息搜索',
        ENTER_CLOUD_HOST_INFORMATION_TO_SEARCH: '输入云主机信息搜索',
        RESET_SEARCH: '重置搜索',
        CLOUD_PLATFORM: '云平台',
        RAM: '内存',
        CONFIGURATION: '配置',
        CURRENT_CONFIGURATION: '当前配置',
        STORAGE: '存储',
        STORAGE_TYPE: '储存类型',
        SNAPSHOT: '快照',
        CONSOLE: '控制台',
        PHYSICAL_MACHINE: '物理机',
        FLOAT: '浮动',
        PATH: '地址',
        SERVICES: '服务',
        INSTANCE: '实例',
        CAPATITY: '容量',
        CAPACITY_GB: '容量(GB)',
        MOUNT: '挂载',
        ZONE: '区域',
        ZONE_DATA_FAILED: '区域加载失败',
        AVAILABLE_ZONE: '可用区',
        AVAILABLE_ZONE_DATA_ERROR: '可用区数据加载错误',
        AREA: '区域',
        REGION_AND_AVAILABLE_AREA: '所在区域及可用区',
        CREATED_TIME: '创建时间',
        EXPIRE_DATE: '到期时间',
        SYSTEM_PROMPT: '系统提示',
        OPERATOR: '操作者',
        EXECUTOR: '执行者',
        DARA_ACQUISITION_FAILURE: '数据获取失败',
        UPDATE_FAILED: '更新失败',

        //ts
        CLOUD_HOST_OPERATION: '云主机操作',
        SUCCESS: '成功！',
        FAILED_TO_GET_DATA: '获取数据失败！',
        //长句子
        SET_NAME_FORMAT: '2-68个字符，以大小写字母或中文开头，可包含数字，"."，"-"，"_"'
    },
    SITE: {
        EXIT: '退出'
    },
    DIALOG: {
        PROMPT: '提示',
        CONFIRM: '确认',
        CANCEL: '取消',
        COMMIT: '提交',
        SAVE: '保存',
        CLOSE: '关闭'
    },
    MENU: {
        CLOUD_HOSTING_SERVICES: '云主机服务',
        CLOUD_HOSTING_INSTANCE: '云主机实例',
        CLOUD_HARD_DISK: '云硬盘',
        VIRTUAL_MACHINE_INSTANCE: '虚拟机实例',
        MIRROR: '镜像',
        PHYSICAL_SERVERS: '物理机服务',
        ACCOUNT_MANAGEMENT: '账号管理',
        EXPENSE_CENTER: '费用中心',
        LOAD_BALANCER: '负载均衡服务器',
        DEPARTMENT_MANAGENMENT: '部门管理',
        AUTHORITY_MANAGEMENT: '权限管理',
        PRICE_SET: '价格设置',
        QUOTA_MANAGEMENT: '配额管理',
        APPROVAL_CENTER: '审批中心',
        NOT_APPROVED: '未审批',
        APPROVED: '已审批',
        PURCHASED_SERVICE_MANAGEMENT: '已购服务管理',
        ORDER_INQUIRY: '订单查询',
        ACCOUNT_CENTER: '用户中心',
        ORGANIZATION_MANAGENMENT: '组织管理',
        PERSONAL_ACCOUNT_MANAGEMENT: '个人账户管理',
        PRODUCTS_SERVICES: '产品与服务',
        CLOUD_HOSTING: '云主机',
        OVERVIEW: '概览',
        ORDER: '订购',
        INSTANCE_LIST: '实例列表'
    },
    VM_INSTANCE: {
        CLOUD_HOST_DETAILS: '云主机详情',
        RETURNS_THE_CLOUD_HOST_LIST: '返回云主机列表',
        MORE_ACTIONS: '更多操作',
        EDIT_THE_CLOUD_HOST: '编辑云主机',
        DELETE_THE_CLOUD_HOST: '删除云主机',
        CONSOLE: '控制台',
        BASIC_INFORMATION: '基本信息',
        INSTANCE_NAME: '实例名称',
        AVAILABLE_AREA: '所在可用区',
        OPERATION_HOURS: '运行时间',
        STATUS: '状态',
        RESOURCE: '来源',
        EXTRA_INFORMATION: '附加信息',
        EXTRA_SERVICES: '附加服务',
        TYPE: '类型',
        SERVICE_LEVEL: '服务级别',
        LABEL: '标签',
        DESCRIPTION: '描述',
        CONFIGURATION_INFORMATION: '配置信息',
        CPU: 'CPU',
        RAM: '内存',
        MIRROR: '镜像',
        INTERNAL_IP: '内部IP',
        EXTERNA_IP: '外部IP',
        DISK_INFORMATION: '磁盘信息',
        BOOT_DISK: '启动盘',
        DATA_DISK: '数据盘',
        SNAPSHOT: '快照：',
        SECURITY_INFORMATION: '安全信息',
        SECURITY_GROUP: '安全组：',
        PAID_INFORMATION: '付费信息',
        ORDER_NUMBER: '订单编号：',
        PAYMENT_METHODS: '付费方式：',
        CREATED_DATE: '创建时间：',
        EXPIRE_DATE: '到期时间：',
        RELEASE_DATE: '释放时间：',

        //cloud-host-list
        REGION_LIST: '区域列表',
        CREATE_CLOUD_HOST: '创建云主机',
        UNSUBSCRIBE_CLOUD_HOST: '退订云主机',
        BIND_FLOATING_IP: '绑定浮动IP',
        UNBIND_FLOATING_IP: '解绑浮动IP',
        VIEW_CONSOLE: '查看控制台',

        //cloud-host-order.html
        NET: '网络',
        NET_TYPE: '网络类型',
        PLEASE_SELECT_SUBNET_YOU_NEED: '请选择您需要的子网网段',
        CONSULT_ADMIN_ABOUT_CHOOSING: '如果您不知道如何选择，请咨询管理员',
        INSTANCE_CONFIGURATION: '实例规格',
        CLOUD_HOST_SOURCE: '云主机源',
        START_SOURCE: '启动源',
        MIRROR_TYPE: '镜像类型',
        MIRROR_LIST: '镜像列表',
        STORE: '储存',
        PASSWARD_SETTING: '密码设置',
        USER_NAME: '用户名',
        LOGIN_PASSWARD: '登录密码',
        PLEASE_ENTER_HOST_PASSWARD: '请输入主机密码',
        CONFIRM_PASSWARD: '确认密码',
        MIRROR_NAME: '镜像名称',
        CLOUD_HOST_COSTS: '云主机费用',
        CLOUD_HARD_DISK_COSTS: '云硬盘费用',
        BY_VOLUMN_COSTS: '按量费用',
        TOTAL_COST: '费用总计',
        ANNUAL_SUBSCRIPTION: '包年包月',
        PRODUCT_ORDER_DESCRIPTION: '不同区域之间的产品内网不互通；订购后不支持更换区域，请谨慎选择！',
        DEFINITION_OF_PUBLIC_IMAGE_AND_CUSTOM_IMAGE: '公共镜像即基础操作系统，自定义镜像为企业根据基础操作系统做过额外配置或优化后的操作系统',
        PASSWARD_COMPLEXITY_DESCRIPTION: '密码复杂度：8-30个字符，且同时包括三项（大写字母，小写字母，数字和特殊符号）',

        //cloud-host-order.ts
        PASSWARD_FORMAT_IS_NOT_CORRECT: '密码格式不正确',
        TWO_PASSWARD_ENTRIES_ARE_INCONSISTENT: '两次密码输入不一致',
        HOST_NAME_FORMAT_IS_NOT_CORRECT: '主机名称格式不正确',
        PURCHASE_DURATION_DESCRIPTION: '请输入购买时长为最大不超过999的数字',
        PLEASE_SELECT_CLOUD_PALTFORM: '请选择云平台',
        PLEASE_SELECT_AVAILABLE_ZONE: '请选择可用区',
        PLEASE_SELECT_CPU: '请选择cpu',
        PLEASE_SELECT_RAM: '请选择内存',
        PLEASE_SELECT_NET_TYPE: '请选择网络类型',
        PLEASE_SELECT_SECURITY_GROUP: '请选择安全组',
        PLEASE_SELECT_STARTUP_SOURCE: '请选择启动源',
        PLEASE_SELECT_IMAGE_TYPE: '请选择镜像类型',
        PLEASE_SELECT_IMAGE_NAME: '请选择镜像名称',


        //sub-add-storage
        ADD_DATA_DISK: '增加数据盘'

    },
    ORDER_MNG: {//_DATA_FAILED
        ORDER_DETAILS: '订购详情',
        ORDERS_DETAILS: '订单详情',
        ORDERS_DETAILS_DATA_FAILED: '订单详情加载失败',
        RENEWAL_FEE: '续订费用',
        RENEWAL_FEE_DATA_FAILED: '续订费用加载失败',
        DEPARTMENT_LIST: '部门列表',
        DEPARTMENT_LIST_DATA_FAILED: '部门列表加载失败',
        SUBSCRIBER_LIST: '订购人列表',
        SUBSCRIBER_LIST_DATA_FAILED: '订购人列表加载失败',
        SUBMITTER_LIST: '提交者列表',
        ORDERS_LSIT: '订单列表',
        ORDERED_LSIT: '已订购列表',
        ORDERED_LSIT_DATA_FAILED: '已订购列表加载失败',
        ONLY_SUCCESS_OR_EXPIRING_ORDERS_CAN_BE_RENEWED: '只有个“成功”或“即将过期”的订单可以续订',
        ONLY_SUCCESS_OR_EXPIRING_ORDERS_CAN_BE_UNSUBSCRIBE: '只有个“已激活”的订单可以退订',
        PURCHASE_TIME: '购买时长',
        PLEASE_ENTER_A_NUMBER_QUERY: '请输入编号查询',
        DUE_DATE: '到期时间',
        THE_CURRENT_QUERY_TO: '当前查询到',
        PURCHASED_SERVICE_PURCHASED_SERVICE_ARE_LISTED_BELOW: '个已购服务，已购服务列表如下',
        CHARGING_MODE: '计费模式',
        PURCHASE_CYCLE: '购买周期',
        RENEWAL_EXPIRATION_TIME: '续订后到期时间',
        YOUR_ORDER_HAS_BEEN_RENEWED___AND_THE_ASSOCIATED_RESOURCES: '你的订单续订已完成，可以进入管理控制台查看订单状态及使用相关资源',
        FOR_APPROVAL___TO_TAKE_EFFECT: '如需审批，则需要订单审批通过后，才能正式生效',
        UNSUBSCRIBE_FROM___HARD_DRIVE: '一起退订该云主机挂载的云硬盘',
        UNSUBSCRIBE_FROM___NO_DRIVE: '你确认要退订该云主机吗',
        WHETHER_TO_CONFIRM___EXIT_THE_PROCESS: '是否确认删除该云硬盘. 如果选"确认", 则卸载该云硬盘并删除. 如果选"取消", 则退出流程',
        WHETHER_TO_CONFIRM_FORCE___EXIT_THE_PROCESS: '是否强制删除. 如果选"确认", 则卸载该云硬盘并删除。 如果选"取消", 则退出流程',
        UNIT_PRICE: '单价费用',
        ASSOCIATED_LIST_OF_SUBSCRIBED_SERVICES: '关联的已订购服务列表',
        ORIGINAL_EXPIRATION_TIME: '原到期时间',
        CONFIRM: '确定',
        ORDER_TRACKING: '订单查询',
        PLEASE_ENTER_THE_ORDER_NUMBER_FUZZY_QUERY: '请输入订单号模糊查询',
        RESET: '重置',
        ORDER_STATUS: '订单状态',
        ALL_STATUS: '所有状态',
        PRODUCT_TYPE: '产品类型',
        ALL_TYPES: '所有类型',
        CURRENT_QUERY_TO: '当前查询到',
        ORDER_ORDER_LIST_IS_AS_FOLLOWS: '订单，订单列表如下：',
        NUMBER: '编号',
        ORDER_NUMBER: '订单编号',
        ORDER_TYPE: '订单类型',
        EXPENSE: '费用',
        SUBMISSION_TIME: '提交时间',
        COMPLETION_TIME: '完成时间',
        SUBMITTER: '提交者',
        DEPARTMENT: '所属部门',
        OPERATION: '操作',
        NONRECURRING_EXPENSE: '一次性费用',
        EXPENSE_$: '费用',
        DETAILS: '详 情',
        ORDER_NUMBER_: '订单号：'
    },
    ORG_MNG_LIST: {
        OPERATION_ERROR: '操作错误',
        ORGANIZATIONAL_STATUS_IS_ENABLED: '组织状态已启用',
        ENABLE_DEPARTMENT: '启用部门',
        YOU_CHOOSE_TO_ENABLE_VALUE_PLEASE_CONFIRM: '您选择启用{{value_1}}，请确认',
        EDIT_DEPARTMENT: '编辑部门',
        YOU_CAN_NOT_DELETE_ORGANIZATIONS_THAT_ARE_ENABLED: '不能删除启用状态下的组织'
    },
    MNG_CONSOLE: {
        OVERVIEW_OF_MANAGEMENT_CONTROL: '管理控制概览',
        PURCHASED_SERVICE: '已购买服务',
        WORK_ORDER_STATISTICS: '工单统计',
        TOTAL_QUOTA_USAGE: '部门配额使用率',
        DEPARTMENT_RESOURCES: '部门资源'
    },
    CHECK_CENTER: {
        //check-mng-list.html
        PENDING_LIST: '待审批列表',
        ENTER_THE_ORDER_NUMBER_OR_DEPARTMENT_FOR_QUICK_INQUIRY: '输入订单号或部门快速查询',
        ADVANCED_SEARCH: '高级查询',
        ORDER_ATTRIBUTION: '订单归属',
        ALL_DEPARTMENTS: '所有部门',
        SUBMITTER: '提交者',
        ALL_SUBMITTERS: '所有提交者',
        ORDER_TYPE: '订单类型',
        ALL_TYPES: '所有类型',
        PRODUCT_TYPE: '产品类型',
        QUERY: '查  询',
        RESET: '重置',
        CURRENT_QUERY_IS: '当前查询到',
        THE_QUERY_RESULTS_OF_PENDING_ORDERS: '个订单需要审批，查询结果如下',

        ORDER_DESCRIPTION: '订单描述',
        DEPARTMENT: '部门',
        ENTERPRISE: '企业',
        COST: '费用',
        APPROVAL_RESULTS: '审批结果',
        BILLING_MODE: '计费模式',
        ORDER_CYCLE: '订单周期',
        ONE_TIME_COSTS: '一次性费用',
        AGREE: '同意',
        REFUSE: '拒绝',
        THE_ORDER_REQUEST_WAS_REJECTED: '订单请求被拒绝',
        REASON: '原因',
        INPUT_CHINESE_OR_CHARACTERS_NOT_MORE_THAN_200_WORDS: '可以输入中文与字符,最大不能超过200个字',

        //check-mng-list.ts
        DEPARTMENTS_LIST: '部门列表',
        SUBMITTERS_LIST: '提交者列表',
        SYSTEM: '系统',
        REFUSE_REASON_DESCRIPTION: '必须填写拒绝原因，且不能超出200字',
        APPROVAL_CONSENT: '审批同意',
        CONFIRM_TO_APPROVE_THE_ORDER: '你确认要审批同意该订单吗？',

        //check-mng-hascheck.html
        APPROVED_LIST: '已审批列表',
        APPROVER: '审批人',
        ALL_APPROVERS: '所有审批人',
        APPROVAL_TIME: '审批时间',
        APPROVAL_COMMENTS: '审批意见',

        //check-mng-set
        APPROVAL_SETTINGS: '审批设置',
        IS_APPROVAL_REQUIRED: '是否需要审批',
        OPEN: '开启',
        CLOSE: '关闭',
        MINUTE: '分钟',
        AUTO_APPROVAL_TIME_SET: '自动审批时间设置',
        EDIT: '编 辑',
        SAVE: '保 存'

    },

    //cloud-drive文件夹下
    CLOUD_DRIVE_LIST: {
        AREA_LIST: '区域列表',
        ADVANCED_SEARCH: '高级搜索',
        CREATE_CLOUD_HRAD_DISK: '创建云硬盘',
        CLOUD_HRAD_DISK_NAME: '云硬盘名称',
        MOUNT_LOCATION_CLOUD_HOST_NAME: '挂载位置（云主机名称）',
        AVAILABLE_AREA: "所在可用区",
        UNSUBSCRIBE_DISK: '退订云硬盘',

        REGION: '所在地区',
        ATTRIBUTE: '属性',
        OPERATE: '操作',
        MOUNT: '挂载',
        UNINSTALL: '卸载',
        MOUNT_CLOUD_HOST: '挂载云主机',


    },
    CLOUD_DRIVE_ORDER: {

        CLOUD_HARD_DISK_ORDER_DESCRIPTION: '云硬盘只能挂载到同一可用区下的云主机实例，订购成功后不支持更换云硬盘的区域和可用区；请谨慎选择',
        CONFIGURATION_OPTIONS: '配置选项',
        BLANK_DISK: '空白盘',
        CLOUD_HARD_DISK_TYPE: '云硬盘类型',
        //73行
        CLOUD_HARD_DISK_INSTANCE_NAME: '云硬盘实例名称',
        //81行
        WHETHER_TO_AMOUNT_ON_CLOUD_HOST: '是否挂载到云主机',
        CLOUD_HOST_INSTANCE_LIST: '云主机实例列表',
        CLOUD_HRAD_DISK_TYPE: '云硬盘类型',
        MOUNT_TO_CLOUD_HOST: '挂载到云主机',

        //TS
        SUCCESSFULLY_ADDED_TO_SHOPPING_CART: '加入购物车成功!',
        PLEASE_SELECT_CLOUD_PLATFORM: '请选择云平台',
        PLEASE_SELECT_AVAILABLE_ZONE: '请选择可用区',
        PLEASE_SELECT_CLOUD_HARD_DISK: '请选择云硬盘',
        PLEASE_SELECT_CLOUD_HARD_DISK_TYPE: '请选择云硬盘类型',
        CLOUD_HARD_DISK_NAME_FORMAT_IS_NOT_CORRECT: '云硬盘名称格式不正确',
        SKU_IS_NOT_CORRECT: 'sku不正确'
    },
    SUB_TABLE_LIST: {
        BACKUP_NAME: '备份名称',
        SOURCE_CLOUD_HARD_DISK_NAME: '源云硬盘名称',
        SOURCE_VIRTUAL_MACHINE_NAME: '源虚拟机名称',
        ENTER_INFORMATION_TO_SEARCH: '输入信息搜索',
        INTERNAL_IP: '内部IP',
        EXTERNAL_IP: '外部IP'
    },
    OS_DISK: {
        //os-disk-list.ts  and  os-disk-order.ts
        CLOUD_HARD_DISK_LIST: '云硬盘列表',
        ORDER_CLOUD_HARD_DISK: '订购云硬盘'
    },
    VM_DISK: {
        //vw-disk-list.ts  and  vw-disk-order.ts
        VMWARE_CLOUD_HARD_DISK_LIST: 'VMware云硬盘列表',
        ORDER_VMWARE_CLOUD_HARD_DISK: '订购VMware云硬盘'
    },
    //shopping-cart文件夹下
    SHOPPING_CART: {
        //cart-list.html
        PRODUCT_INFORMATION: '产品信息',
        PRODUCT_TYPE: '产品类型',
        PURCHASE_CYCLE: '购买周期',
        CHARGE_DETAIL: '费用明细',
        QUANTITY: '数量',
        NOTE: '小记',
        REMOVE_FROM_CART: '从购物车中移除',
        INCREMENTAL_CYCLE_COST: '增量周期费用',
        UNIT_PRICE: '单价费用',
        SET: '台',
        BACK_TO_PRODUCT_PURCHASE: '<返回产品购买',
        SETTLE_ACCOUNTS: '下单结算',
        TOTAL_COST: '( 费用合计 )',

        //cart-order.html
        ORDER_FINISHED: '订单完成',
        MNG_CONSOLE: '管理控制台',
        ORDER_HAS_BEEN_GENERATED: '您的订单已生成，可以进入管理控制台查看订单状态及使用相关资源',
        ORDER_IS_EFFECTIVE_AFTER_APPROVED: '如需审批，则需要订单审批通过后，才能正式生效。',

        //ts
        SUCCESSFULLY_EMPTY_SHOPPING_CART: '清空购物车成功!',
        SURE_TO_EMPTY_EMPTY_SHOPPING_CART: '你确定要清空购物车吗？',
        SUCCESSFULLY_DELETED: '删除成功!',
        DELETE_FAILED: '删除失败',
        CONFIRM_TO_DELETE: '你确定要删除吗？',
        PURCHASE_SUCCESS: '购买成功！',
        PURCHASE_FAILED: '购买失败',
    },
    IMAGE: {
        AREA_LIST: '区域列表',
        IMAGE_ATTRIBUTION: '镜像归属',
        IMAGE_NAME: '镜像名称',
        ENETR_IMAGE_NAME_TO_SEARCH: '输入镜像名称搜索',
        OPERATING_SYSTEM: '操作系统',
        IMAGE_TYPE: '镜像类型',
        SIMPLE_SEARCH: '简单搜索',
        RESET_OPTIONS: '重置选项',
        CHOOSE: '选择',
        SYSTEM_BITS: '系统位数',
        IMAGE_CAPACITY: '镜像容量',
        FOUNDER: '创建人',
        CREATED_DEPARTMENT: '创建部门',
        PROGRESS_RATE: '进度',
        CUSTOM_IMAGE_NAME: '自定义镜像名',
        CUSTOM_IMAGE_APPLICATION_RANGE: '自定义镜像应用范围',
        CUSTOM_IMAGE_DESCRIPTION: '自定义镜像描述',

        //TS
        IMAGE_NAME_CAN_NOT_BE_BLANK: '镜像名称不能为空',
        EDIT_IMAGE: '编辑镜像'

    },
    CLOUD_HOST: {
        FAILED_TO_RETRIEVE_INSTANCE_DETAILS: '实例详细信息获取失败',
        PLEASE_SELECT_A_SERVICE_DIRECTORY: '请选择一个服务目录',
        PLEASE_SELECT_ONLY_ONE_SERVICE_DIRECTORY: '请只选择一个服务目录',
        INSTANCE_STATUS_UPDATE_FAILED: '实例状态更新失败',
        FAILED_TO_GET_THE_ORDER_LIST_DATA: '可订购列表数据获取失败',
        CONFIGURATION_SUBMISSION_FAILED___CONTACT_ADMINISTRATOR: '配置申请提交失败，请重新尝试或者联络管理员',
        CONFIGURATION_APPLICATION_SUBMITTED_SUCCESSFULLY: '配置申请提交成功'.
    }
}