export const TranslateCN = {
    LANG: '中文',
    COMMON: {
        PROMPT: '提示',
        CONFIRM: '确认',
        CANCEL: '取消',
        EXIT: '退出',
        RESET: '重置',
        NUMBER: '编号',
        OPERATION: '操作',
        TYPE: '类型',
        DESCRIPTION: '描述',
        ORDER: '订购',
        OVERVIEW: '概览',
        LABEL: '标签',
        EXPENSE: '费用',
        ONE_TIME_COSTS: '一次性费用',
        TOTAL_COST: '费用总计',
        BY_VOLUMN:'按量',
        DETAILS: '详情',
        BUY_NOW: '立即购买',
        SHOPPING_CART:'购物车',
        ADD_TO_SHOPPING_CART: '加入购物车',
        CHECK_SHOPPING_CART: '查看购物车',
        EMPTY_SHOPPING_CART: '清空购物车',
        NAME: '名称',
        NONE: '无',
        ALL:'所有',
        
        //单位
        $:"￥",

        //状态名词
        ENABLED: '已启用',
        NOT_ENABLED: '未启用',
        NOT_APPROVED: '未审批',
        APPROVED: '已审批',
        NEWLY_CREATED: '新创建',
        IN_PROCESS: '处理中',
        COMPLETED: '已完成',

        //专业术语
        MIRROR: '镜像',
        CLOUD_HOSTING: '云主机',
        CLOUD_HOST_NAME:'云主机名称',
        CLOUD_HARD_DISK: '云硬盘',
        CLOUD_HRAD_DISK_NAME: '云硬盘名称',
        ENTER_CLOUD_HARD_DISK_INFORMATION_TO_SEARCH:'输入云硬盘信息搜索',
        CLOUD_PLATFORM:'云平台',     
        RAM: '内存',
        CONFIGURATION:'配置',
        STORAGE: '存储',
        STORAGE_TYPE: '储存类型',
        SNAPSHOT: '快照',
        CONSOLE: '控制台',
        PHYSICAL_MACHINE: '物理机',
        FLOAT: '浮动',
        PATH: '地址',
        SERVICES: '服务',
        INSTANCE: '实例',
        CAPATITY: '容量',
        CAPACITY_GB:'容量(GB)',
        MOUNT: '挂载',
        AVAILABLE_ZONE: '可用区',
        PURCHASE_AMOUNT:'购买量',
    },
    SITE: {
        EXIT: '退出'
    },
    DIALOG: {
        PROMPT: '提示',
        CONFIRM: '确认',
        CANCEL: '取消'
    },
    MENU: {
        CLOUD_HOSTING_SERVICES: '云主机服务',
        CLOUD_HOSTING_INSTANCE: '云主机实例',
        CLOUD_HARD_DISK: '云硬盘',
        VIRTUAL_MACHINE_INSTANCE: '虚拟机实例',
        MIRROR: '镜像',
        PHYSICAL_SERVERS: '物理机服务',
        ACCOUNT_MANAGEMENT: '账号管理',
        EXPENSE_CENTER: '费用中心',
        LOAD_BALANCER: '负载均衡服务器',
        DEPARTMENT_MANAGENMENT: '部门管理',
        AUTHORITY_MANAGEMENT: '权限管理',
        PRICE_SET: '价格设置',
        QUOTA_MANAGEMENT: '配额管理',
        APPROVAL_CENTER: '审批中心',
        NOT_APPROVED: '未审批',
        APPROVED: '已审批',
        PURCHASED_SERVICE_MANAGEMENT: '已购服务管理',
        ORDER_INQUIRY: '订单查询',
        ACCOUNT_CENTER: '用户中心',
        ORGANIZATION_MANAGENMENT: '组织管理',
        PERSONAL_ACCOUNT_MANAGEMENT: '个人账户管理',
        PRODUCTS_SERVICES: '产品与服务',
        CLOUD_HOSTING: '云主机',
        OVERVIEW: '概览',
        ORDER: '订购',
        INSTANCE_LIST: '实例列表'
    },
    VM_INSTANCE: {
        CLOUD_HOST_DETAILS: '云主机详情',
        RETURNS_THE_CLOUD_HOST_LIST: '返回云主机列表',
        MORE_ACTIONS: '更多操作',
        EDIT_THE_CLOUD_HOST: '编辑云主机',
        DELETE_THE_CLOUD_HOST: '删除云主机',
        CONSOLE: '控制台',
        BASIC_INFORMATION: '基本信息',
        INSTANCE_NAME: '实例名称：',
        AVAILABLE_AREA: '所在可用区：',
        OPERATION_HOURS: '运行时间：',
        STATUS: '状态：',
        RESOURCE: '来源：',
        EXTRA_INFORMATION: '附加信息',
        EXTRA_SERVICES: '附加服务：',
        TYPE: '类型：',
        SERVICE_LEVEL: '服务级别：',
        LABEL: '标签：',
        DESCRIPTION: '描述：',
        CONFIGURATION_INFORMATION: '配置信息',
        CPU: 'CPU：',
        RAM: '内存：',
        MIRROR: '镜像：',
        INTERNAL_IP: '内部IP：',
        EXTERNA_IP: '外部IP：',
        DISK_INFORMATION: '磁盘信息',
        STARTUP_DISK: '启动盘：',
        DATA_DISK: '数据盘：',
        SNAPSHOT: '快照：',
        SECURITY_INFORMATION: '安全信息',
        SECURITY_GROUP: '安全组：',
        PAID_INFORMATION: '付费信息',
        ORDER_NUMBER: '订单编号：',
        PAYMENT_METHODS: '付费方式：',
        CREATED_DATE: '创建时间：',
        EXPIRE_DATE: '到期时间：',
        RELEASE_DATE: '释放时间：',
    },
    ORDER_MNG_SEARCH: {
        CONFIRM: '确定',
        ORDER_TRACKING: '订单查询',
        PLEASE_ENTER_THE_ORDER_NUMBER_FUZZY_QUERY: '请输入订单号模糊查询',
        RESET: '重置',
        ORDER_STATUS: '订单状态：',
        ALL_STATUS: '所有状态：',
        PRODUCT_TYPE: '产品类型：',
        ALL_TYPES: '所有类型：',
        CURRENT_QUERY_TO: '当前查询到',
        ORDER_ORDER_LIST_IS_AS_FOLLOWS: '订单，订单列表如下：',
        NUMBER: '编号',
        ORDER_NUMBER: '订单编号',
        ORDER_TYPE: '订单类型',
        EXPENSE: '费用',
        SUBMISSION_TIME: '提交时间',
        COMPLETION_TIME: '完成时间',
        SUBMITTER: '提交者',
        DEPARTMENT: '所属部门',
        OPERATION: '操作',
        NONRECURRING_EXPENSE: '一次性费用：￥',
        EXPENSE_$: '费用：￥',
        DETAILS: '详 情',
        ORDER_NUMBER_: '订单号：'
    },
    ORG_MNG_LIST: {
        OPERATION_ERROR: '操作错误',
        ORGANIZATIONAL_STATUS_IS_ENABLED: '组织状态已启用',
        ENABLE_DEPARTMENT: '启用部门',
        YOU_CHOOSE_TO_ENABLE_VALUE_PLEASE_CONFIRM: '您选择启用{{value}}，请确认',
        EDIT_DEPARTMENT: '编辑部门',
        YOU_CAN_NOT_DELETE_ORGANIZATIONS_THAT_ARE_ENABLED: '不能删除启用状态下的组织'
    },
    MNG_CONSOLE: {
        OVERVIEW_OF_MANAGEMENT_CONTROL: '管理控制概览',
        PURCHASED_SERVICE: '已购买服务',
        WORK_ORDER_STATISTICS: '工单统计',
        TOTAL_QUOTA_USAGE: '总配额使用率',
        DEPARTMENT_RESOURCES: '部门资源',
    }
}