export const TranslateEN = {
    test: 'abc{{value}}',
    LANG: 'ENGLISH',
    COMMON: {
        PROMPT: 'prompt',
        CONFIRM: 'confirm',
        CANCEL: 'cancel',
        EXIT: 'exit',
        DELETE: 'delete',
        RESET: 'reset',
        NUMBER: 'number',
        SAVE: 'save',
        ORDER_NUMBER: 'order number',
        ORDER_ID: 'order ID',
        OPERATION: 'operation',
        MORE_ACTIONS: 'more options',
        STATUS: 'status',
        TYPE: 'type',
        DESCRIPTION: 'description',
        ORDERS: 'orders',
        ORDER: 'order',
        OVERVIEW: 'summary',
        LABEL: 'label',
        EXPENSE: 'cost',
        TOTAL_EXPENSE: 'total expense',
        ONE_TIME_COSTS: 'one time cost',
        PAYMENT_METHODS: 'payment methods',
        TOTAL_COST: 'total cost',
        BILLING_MODE: 'billing mode',
        BY_VOLUMN: 'by volumn',
        DETAILS: 'details',
        BUY_NOW: 'buy now',
        SHOPPING_CART: 'shopping cart',
        PURCHASE_AMOUNT: 'purchase amount',
        PURCHASE_DURATION: 'purchase duration',
        ADD_TO_SHOPPING_CART: 'add to the shopping cart ',
        CHECK_SHOPPING_CART: 'check the shopping cart',
        EMPTY_SHOPPING_CART: 'empty the shopping cart',
        NAME: 'name',
        NONE: 'none',
        ALL: 'all',
        DEPARTMENT: 'department',
        PURCHASER: 'purchaser',
        PRODUCT: 'product',
        PURCHASED: 'prurchased',
        QUANTITY: 'quantity',
        PRICE: 'price',
        PERMANENCE: 'permanence',
        MANAGEMENT: 'management',
        INFORMATION: 'information',
        BASIC: 'basic',
        ENTERPRISE: 'enterprise',
        DATE: 'date',
        HISTORY: 'history',
        EXPLAIN: 'explaination',
        USERS: 'users',
        WARNING: 'warning',
        PLEASE_WAIT: 'please wait',
        ADD: 'add',
        UPDATE: 'update',
        QUERY: 'query',
        PUBLIC: 'public',
        PRIVATE: 'private',
        LIST: 'list',
        VIEW: 'view',
        EDIT: 'edit',
        CREATE: 'create',
        SEARCH: 'search',
        SELECT_ALL: 'select all',
        SELECT: 'select',
        SPECIFICATION: 'specification',
        PHONE: 'phone',
        ACCOUNT: 'account',
        TOTAL: 'total',
        REMAIN: 'remain',
        LOCAL: 'local',
        PASSWORD: 'password',

        //单位
        $: "$ ",
        YUAN: '',
        GB: 'GB',
        ONE_SET: 'one set',
        TWO_SET: 'two set',
        THREE_SET: 'three set',
        FOUR_SET: 'four set',
        FIVE_SET: 'five set',
        CORE: 'core',

        //状态名词
        ENABLED: 'enabled',
        ENABLE: 'enable',
        DISENABLED: 'disabled',
        NOT_ENABLED: 'not enabled',
        NOT_APPROVED: 'yet approved',
        APPROVED: 'approved',
        NEWLY_CREATED: 'newly created',
        IN_PROCESS: 'in process',
        COMPLETED: 'completed',
        UNSUBSCRIBE: 'unsubscribe',
        RENEW: 'renew',
        RENEW_DATA_FAILED: 'renew failure',
        START: 'start',
        SHUTDOWN: 'shutdown',
        PAUSE: 'pause',
        RESTORE: 'restore',
        HARD_REBOOT: 'hard reboot',
        SOFT_RESTART: 'soft restart',
        RUNNING: 'running',
        PENDING: 'suspending',
        DELETED: 'deleted',


        //专业术语
        MIRROR: 'image',
        CLOUD_HOSTING: 'cloud hosting',
        CLOUD_HOST_NAME: 'cloud hostname',
        CLOUD_HARD_DISK: 'cloud hard disk',
        CLOUD_HRAD_DISK_NAME: 'cloud hard disk name',
        ENTER_CLOUD_HARD_DISK_INFORMATION_TO_SEARCH: 'enter the cloud hard disk search information',
        ENTER_CLOUD_HOST_INFORMATION_TO_SEARCH: 'enter the cloud hard disk search information',
        RESET_SEARCH: 'reset search',
        CLOUD_PLATFORM: 'cloud platform',
        RAM: 'RAM',
        CONFIGURATION: 'configuration',
        CURRENT_CONFIGURATION: 'current configuration',
        STORAGE: 'storage',
        STORAGE_TYPE: 'storage type',
        SNAPSHOT: 'snapshot',
        CONSOLE: 'console',
        PHYSICAL_MACHINE: 'physical machine',
        FLOAT: 'float',
        PATH: 'path',
        SERVICES: 'services',
        INSTANCE: 'instance',
        INSTANCE_CONFIGURATION: 'instance flavor',
        CAPATITY: 'capatity',
        CAPACITY_GB: 'capatity (GB)',
        MOUNT: 'mount',
        ZONE: 'zone',
        ZONE_DATA_FAILED: 'Zone data error',
        AVAILABLE_ZONE: 'avilable zone',
        AVAILABLE_ZONE_DATA_ERROR: 'available zone mount failure',
        AREA: 'zone',
        REGION_AND_AVAILABLE_AREA: 'region and available zone',
        CREATED_TIME: 'created time',
        EXPIRE_DATE: 'expiration date',
        SYSTEM: 'system',
        SYSTEM_PROMPT: 'system prompt',
        OPERATOR: 'operator',
        EXECUTOR: 'executor',
        DATA_ACQUISITION_FAILURE: 'data acquisition failure',
        UPDATE_FAILED: 'update failure',
        NETWORK: 'network',
        CLASSIC: 'classic',
        DISK: 'disk',
        MONITORING: 'monitoring',
        USER_NAME: 'user name',

        //ts
        CLOUD_HOST_OPERATION: 'cloud host operation',
        SUCCESS: 'success',
        FAILED_TO_GET_DATA: 'data retrieve failure',
        OPERATION_ERROR: 'operation error',
        OPERATION_SUC: 'operation succeeded',

        //长句子
        SET_NAME_FORMAT: '2-68 characters, begin with uppercase/lower case letter or Chinese, may contain numbers, ".", "-", "_"'
    },
    SITE: {
        EXIT: 'exit',
        MNG_CONSOLE: 'management console',
    },
    DIALOG: {
        PROMPT: 'prompt',
        CONFIRM: 'confirm',
        CANCEL: 'cancel',
        COMMIT: 'commit',
        SAVE: 'save',
        CLOSE: 'close'
    },
    MENU: {
        CLOUD_HOSTING_SERVICES: 'cloud hosting services',
        CLOUD_HOSTING_INSTANCE: 'cloud hosting instance',
        CLOUD_HARD_DISK: 'cloud hard disk',
        VIRTUAL_MACHINE_INSTANCE: 'virtual machine instance',
        MIRROR: 'image',
        PHYSICAL_SERVERS: 'physical servers',
        ACCOUNT_MANAGEMENT: 'account management',
        EXPENSE_CENTER: 'cost center',
        LOAD_BALANCER: 'load balancer',
        DEPARTMENT_MANAGENMENT: 'department management',
        AUTHORITY_MANAGEMENT: 'authority management',
        PRICE_SET: 'price set',
        QUOTA_MANAGEMENT: 'quota management',
        APPROVAL_CENTER: 'approval center',
        NOT_APPROVED: 'yet approved',
        APPROVED: 'approved',
        PURCHASED_SERVICE_MANAGEMENT: 'purchased service management',
        ORDER_INQUIRY: 'order inquiry',
        ACCOUNT_CENTER: 'account center',
        ORGANIZATION_MANAGEMENT: 'organization management',
        PERSONAL_ACCOUNT_MANAGEMENT: 'personal account management',
        PRODUCTS_SERVICES: 'products and services',
        CLOUD_HOSTING: 'cloud hosting',
        OVERVIEW: 'summary',
        ORDER: 'order',
        INSTANCE_LIST: 'instance list'
    },
    VM_INSTANCE: {
        CLOUD_HOST_DETAILS: 'cloud host details',
        RETURNS_THE_CLOUD_HOST_LIST: 'return to the cloud host list',
        MORE_ACTIONS: 'more options',
        EDIT_THE_CLOUD_HOST: 'edit the cloud host',
        DELETE_THE_CLOUD_HOST: 'delete the cloud host',
        CONSOLE: 'console',
        BASIC_INFORMATION: 'basic information',
        INSTANCE_NAME: 'instance name',
        AVAILABLE_AREA: 'avilable zone',
        OPERATION_HOURS: 'operation hours',
        STATUS: 'status',
        RESOURCE: 'resource',
        EXTRA_INFORMATION: 'extra information',
        EXTRA_SERVICES: 'extra services',
        TYPE: 'type',
        SERVICE_LEVEL: 'service level',
        LABEL: 'label',
        DESCRIPTION: 'description',
        CONFIGURATION_INFORMATION: 'configuration information',
        CPU: 'CPU',
        RAM: 'RAM',
        MIRROR: 'image',
        INTERNAL_IP: 'internal IP',
        EXTERNA_IP: 'externa IP',
        DISK_INFORMATION: 'disk information',
        BOOT_DISK: 'boot disk',
        DATA_DISK: 'data disk',
        SNAPSHOT: 'snapshot',
        SECURITY_INFORMATION: 'security information',
        SECURITY_GROUP: 'security group',
        PAID_INFORMATION: 'payment information',
        ORDER_NUMBER: 'order number',
        PAYMENT_METHODS: 'payment methods',
        CREATED_DATE: 'created date',
        EXPIRE_DATE: 'expiration date',
        RELEASE_DATE: 'release date',

        //cloud-host-list
        REGION_LIST: 'region list',
        CREATE_CLOUD_HOST: 'create cloud host',
        UNSUBSCRIBE_CLOUD_HOST: 'unsubscribe cloud host',
        BIND_FLOATING_IP: 'bind floating IP',
        UNBIND_FLOATING_IP: 'unbind floating IP',
        VIEW_CONSOLE: 'view console',

        //cloud-host-order.html
        NET: 'network',
        NET_TYPE: 'network type',
        PLEASE_SELECT_SUBNET_YOU_NEED: 'please select the subnet you need',
        CONSULT_ADMIN_ABOUT_CHOOSING: 'If you do not know how to choose, please consult the administrator',
        INSTANCE_CONFIGURATION: 'instance flavor',
        CLOUD_HOST_SOURCE: 'cloud host source',
        START_SOURCE: 'start source',
        MIRROR_TYPE: 'image type',
        MIRROR_LIST: 'image list',
        STORE: 'storage',
        PASSWORD_SETTING: 'password setting',
        USER_NAME: 'user name',
        LOGIN_PASSWORD: 'login password',
        PLEASE_ENTER_HOST_PASSWORD: 'please enter the host password',
        CONFIRM_PASSWORD: 'confirm password',
        MIRROR_NAME: 'image name',
        CLOUD_HOST_COSTS: 'cloud host cost',
        CLOUD_HARD_DISK_COSTS: 'cloud hard disk cost',
        BY_VOLUMN_COSTS: 'by volumn cost',
        TOTAL_COST: 'total cost',
        ANNUAL_SUBSCRIPTION: 'annual subscription',
        PRODUCT_ORDER_DESCRIPTION: 'The internal networks of different region prouducts cannot communicate each other; Once purchased, the region cannot be changed, please choose  carefully!',
        DEFINITION_OF_PUBLIC_IMAGE_AND_CUSTOM_IMAGE: "Public image is the basic operating system, customized image is the image with the additional configuration or optimization from the basic operating system, according to the enterprise's requirement",
        PASSWORD_COMPLEXITY_DESCRIPTION: 'password complexity: 8-30 characters, and also includes three items (uppercase letters, lowercase letters, numbers and special symbols)',

        //cloud-host-order.ts
        PASSWORD_FORMAT_IS_NOT_CORRECT: 'password format is not correct',
        TWO_PASSWORD_ENTRIES_ARE_INCONSISTENT: 'two password entries are inconsistent',
        HOST_NAME_FORMAT_IS_NOT_CORRECT: 'host name format is not correct',
        PURCHASE_DURATION_DESCRIPTION: 'purchase duration description',
        PLEASE_SELECT_CLOUD_PALTFORM: 'please select the cloud platform',
        PLEASE_SELECT_AVAILABLE_ZONE: 'please select the available zone',
        PLEASE_SELECT_CPU: 'please select CPUs',
        PLEASE_SELECT_RAM: 'please select RAM',
        PLEASE_SELECT_NET_TYPE: 'please select the network type',
        PLEASE_SELECT_SECURITY_GROUP: 'please select the security group',
        PLEASE_SELECT_STARTUP_SOURCE: 'please select the startup source',
        PLEASE_SELECT_IMAGE_TYPE: 'please select the image type',
        PLEASE_SELECT_IMAGE_NAME: 'please select the image name',
        PLEASE_SELECT_TIMELINE_UNIT: 'please select the timeline unit',


        //sub-add-storage
        ADD_DATA_DISK: 'add data disk',
        ADD_HEAD: 'total can increase',
        ADD_MIDDLE: 'disks,also can increase',
        ADD_TAIL: 'disks'

    },
    ORDER_MNG: {//_DATA_FAILED
        ORDER_DETAILS: 'order details',
        ORDERS_DETAILS: 'orders details',
        ORDERS_DETAILS_DATA_FAILED: 'orders details data error',
        RENEWAL_FEE: 'renewal fee',
        RENEWAL_FEE_DATA_FAILED: 'renewal fee data error',
        DEPARTMENT_LIST: 'department list',
        DEPARTMENT_LIST_DATA_FAILED: 'department list data error',
        SUBSCRIBER_LIST: 'subscriber list',
        SUBSCRIBER_LIST_DATA_FAILED: 'subscriber list data error',
        SUBMITTER_LIST: 'submitter list',
        ORDERS_LIST: 'orders list',
        ORDERED_LIST: 'ordered list',
        ORDERED_LIST_DATA_FAILED: 'ordered list data error',
        ONLY_SUCCESS_OR_EXPIRING_ORDERS_CAN_BE_RENEWED: 'only successful or expired orders can be renewed',
        ONLY_SUCCESS_OR_EXPIRING_ORDERS_CAN_BE_UNSUBSCRIBE: 'only successful or expired orders can be unsubscribe',
        PURCHASE_TIME: 'purchase time',
        PLEASE_ENTER_A_NUMBER_QUERY: 'please enter the query number',
        DUE_DATE: 'due date',
        THE_CURRENT_QUERY_TO: 'the current query to',
        PURCHASED_SERVICE_PURCHASED_SERVICE_ARE_LISTED_BELOW: 'purchased services, purchased service list is as follows',
        CHARGING_MODE: 'charging mode',
        PURCHASE_CYCLE: 'purchase cycle',
        RENEWAL_EXPIRATION_TIME: 'renewal expiration time',
        YOUR_ORDER_HAS_BEEN_RENEWED___AND_THE_ASSOCIATED_RESOURCES: 'Your renewal process is completed, you can  enter the management console to view order status and related resources',
        FOR_APPROVAL___TO_TAKE_EFFECT: 'The order will be taken effective after approval',
        UNSUBSCRIBE_FROM___HARD_DRIVE: 'unsubscribe with mounted cloud hard drive',
        UNSUBSCRIBE_FROM___NO_DRIVE: 'unsubscribe with unmounted cloud hard drive',
        WHETHER_TO_CONFIRM___EXIT_THE_PROCESS: 'Confirm to remove the cloud hard disk, if you select "confirm", then the cloud hard disk is unmounted and removed. If you choose "cancel", the process is canceled.',
        WHETHER_TO_CONFIRM_FORCE___EXIT_THE_PROCESS: 'force to remove the cloud hard disk, if you select "confirm", then the cloud hard disk is unmounted and removed. If you choose "cancel", the process is canceled.',
        UNIT_PRICE: 'unit price',
        ASSOCIATED_LIST_OF_SUBSCRIBED_SERVICES: 'associated subscription service list',
        ORIGINAL_EXPIRATION_TIME: 'original expiration time',
        CONFIRM: 'confirm',
        ORDER_TRACKING: 'order tracking',
        PLEASE_ENTER_THE_ORDER_NUMBER_FUZZY_QUERY: 'please enter the order number fuzzy query',
        RESET: 'reset',
        ORDER_STATUS: 'order status',
        ALL_STATUS: 'all status',
        PRODUCT_TYPE: 'product type',
        ALL_TYPES: 'all types',
        CURRENT_QUERY_TO: 'current query to',
        ORDER_ORDER_LIST_IS_AS_FOLLOWS: 'orders, order list is as follows',
        NUMBER: 'number',
        ORDER_NUMBER: 'order number',
        ORDER_TYPE: 'order type',
        EXPENSE: 'cost',
        SUBMISSION_TIME: 'submission time',
        COMPLETION_TIME: 'completion time',
        SUBMITTER: 'submitter',
        DEPARTMENT: 'department',
        OPERATION: 'operation',
        NONRECURRING_EXPENSE: 'one time cost',
        EXPENSE_$: 'cost',
        DETAILS: 'details',
        ORDER_NUMBER_: 'order number'
    },
    ORG_MNG_LIST: {
        OPERATION_ERROR: 'operation error',
        ORGANIZATIONAL_STATUS_IS_ENABLED: 'organizational status is enabled',
        ENABLE_DEPARTMENT: 'enable department',
        YOU_CHOOSE_TO_ENABLE_VALUE_PLEASE_CONFIRM: 'you have chosen to enable {{value_1}}, please confirm',
        EDIT_DEPARTMENT: 'edit department',
        YOU_CAN_NOT_DELETE_ORGANIZATIONS_THAT_ARE_ENABLED: 'you can not delete organizations that are enabled'
    },
    MNG_CONSOLE: {
        OVERVIEW_OF_MANAGEMENT_CONTROL: 'overview of management control',
        PURCHASED_SERVICE: 'purchased service',
        WORK_ORDER_STATISTICS: 'work order statistics',
        TOTAL_QUOTA_USAGE: 'total quota usage',
        DEPARTMENT_RESOURCES: 'department resource'
    },
    CHECK_CENTER: {
        //check-mng-list.html
        PENDING_LIST: 'pending list',
        ENTER_THE_ORDER_NUMBER_OR_DEPARTMENT_FOR_QUICK_INQUIRY: 'enter the ordernumber or department for quick search',
        ADVANCED_SEARCH: 'advanced serch',
        ORDER_ATTRIBUTION: 'order attribution',
        ALL_DEPARTMENTS: 'all departments',
        SUBMITTER: 'submitter',
        ALL_SUBMITTERS: 'all submitters',
        ORDER_TYPE: 'order type',
        ALL_TYPES: 'all types',
        PRODUCT_TYPE: 'product type',
        QUERY: 'query',
        RESET: 'reset',
        CURRENT_QUERY_IS: 'current query is',
        THE_QUERY_RESULTS_OF_PENDING_ORDERS: 'orders need to be approved, the results are as follows',

        ORDER_DESCRIPTION: 'order description',
        DEPARTMENT: 'department',
        ENTERPRISE: 'enterprise',
        COST: 'COST',
        APPROVAL_RESULTS: 'approval results',
        BILLING_MODE: 'billing mode',
        ORDER_CYCLE: 'order cycle',
        ONE_TIME_COSTS: 'one time cost',
        AGREE: 'agree',
        REFUSE: 'reject',
        THE_ORDER_REQUEST_WAS_REJECTED: 'the order request was rejected',
        REASON: 'reason',
        INPUT_CHINESE_OR_CHARACTERS_NOT_MORE_THAN_200_WORDS: 'chinese characters can be input, the maximum not more than 200 words',

        //check-mng-list.ts
        DEPARTMENTS_LIST: 'department list',
        SUBMITTERS_LIST: 'submitter list',
        SYSTEM: 'system',
        REFUSE_REASON_DESCRIPTION: 'You must fill the rejection reason and it cannot exceed 200 words ',
        APPROVAL_CONSENT: 'approval consent',
        CONFIRM_TO_APPROVE_THE_ORDER: 'Are you sure to approve the order?',

        //check-mng-hascheck.html
        APPROVED_LIST: 'approved list',
        APPROVER: 'approver',
        ALL_APPROVERS: 'all approvers',
        APPROVAL_TIME: 'approval time',
        APPROVAL_COMMENTS: 'approval comments',

        //check-mng-set
        APPROVAL_SETTINGS: 'approval settings',
        IS_APPROVAL_REQUIRED: 'is approval required',
        OPEN: 'open',
        CLOSE: 'close',
        MINUTE: 'minute',
        AUTO_APPROVAL_TIME_SET: 'auto approval time set',
        EDIT: 'edit',
        SAVE: 'save'

    },

    //cloud-drive文件夹下
    CLOUD_DRIVE_LIST: {
        AREA_LIST: 'Region list',
        ADVANCED_SEARCH: 'advanced search',
        CREATE_CLOUD_HRAD_DISK: 'create cloud hard disk',
        CLOUD_HRAD_DISK_NAME: 'cloud hard disk name',
        MOUNT_LOCATION_CLOUD_HOST_NAME: 'the mount point (cloud host name)',
        AVAILABLE_AREA: "available area",
        UNSUBSCRIBE_DISK: 'unsubscribe disk',

        REGION: 'region',
        ATTRIBUTE: 'attribute',
        OPERATE: 'operate',
        MOUNT: 'mount',
        UNINSTALL: 'unmount',
        MOUNT_CLOUD_HOST: 'mount cloud host',


    },
    CLOUD_DRIVE_ORDER: {

        CLOUD_HARD_DISK_ORDER_DESCRIPTION: 'Cloud hard disk can only be mounted on the cloud host instance in the same available zone, Once purchased, the region/available zone  cannot be changed, please choose  carefully!',
        CONFIGURATION_OPTIONS: 'configuration option',
        BLANK_DISK: 'blank disk',
        CLOUD_HARD_DISK_TYPE: 'cloud hard disk type',
        //73行
        CLOUD_HARD_DISK_INSTANCE_NAME: 'cloud hard disk instance name',
        //81行
        WHETHER_TO_AMOUNT_ON_CLOUD_HOST: 'whether to mount on the cloud host',
        CLOUD_HOST_INSTANCE_LIST: 'cloud host instance list',
        CLOUD_HRAD_DISK_TYPE: 'cloud hard disk type',
        MOUNT_TO_CLOUD_HOST: 'mount to cloud host',
        BUY_HEAD: 'you can buy a',
        BUY_MID_FIRST: 'GB cloud disk',
        BUY_MID_SECOND: 'GB onwards, an increase in accordance with each',
        BUY_TAIL: 'GB level',

        //TS
        SUCCESSFULLY_ADDED_TO_SHOPPING_CART: 'successfully added to the shopping cart ',
        PLEASE_SELECT_CLOUD_PLATFORM: 'please select the cloud platform',
        PLEASE_SELECT_AVAILABLE_ZONE: 'please select the available zone',
        PLEASE_SELECT_CLOUD_HARD_DISK: 'please select the cloud hard disk',
        PLEASE_SELECT_CLOUD_HARD_DISK_TYPE: 'please select the cloud hard disk type ',
        CLOUD_HARD_DISK_NAME_FORMAT_IS_NOT_CORRECT: 'cloud hard disk name format is not correct',
        SKU_IS_NOT_CORRECT: 'sku is not correct'
    },
    SUB_TABLE_LIST: {
        BACKUP_NAME: 'backup name',
        SOURCE_CLOUD_HARD_DISK_NAME: 'source cloud hard disk name',
        SOURCE_VIRTUAL_MACHINE_NAME: 'source virtual machine name',
        ENTER_INFORMATION_TO_SEARCH: 'enter the search information ',
        INTERNAL_IP: 'internal IP',
        EXTERNAL_IP: 'external IP'
    },
    OS_DISK: {
        //os-disk-list.ts  and  os-disk-order.ts
        CLOUD_HARD_DISK_LIST: 'cloud hard disk list',
        ORDER_CLOUD_HARD_DISK: 'order cloud hard disk'
    },
    VM_DISK: {
        //vw-disk-list.ts  and  vw-disk-order.ts
        VMWARE_CLOUD_HARD_DISK_LIST: 'VMware cloud hard disk list',
        ORDER_VMWARE_CLOUD_HARD_DISK: 'order vwware cloud hard disk'
    },
    //shopping-cart文件夹下
    SHOPPING_CART: {
        //cart-list.html
        PRODUCT_INFORMATION: 'product information',
        PRODUCT_TYPE: 'product type',
        PURCHASE_CYCLE: 'purchase cycle',
        CHARGE_DETAIL: 'charge detail',
        QUANTITY: 'quantity',
        NOTE: 'note',
        BASICPRICE : 'basic cycle cost',
        UNITARR: "unit charge",
        BILLINGARR: "cycle cost",
        REMOVE_FROM_CART: 'remove from the shopping cart',
        INCREMENTAL_CYCLE_COST: 'incremental cycle cost',
        UNIT_PRICE: 'unit price',
        SET: 'set',
        BACK_TO_PRODUCT_PURCHASE: '< back to product purchase',
        SETTLE_ACCOUNTS: 'settle accounts',
        TOTAL_COST: '( total cost)',

        //cart-order.html
        ORDER_FINISHED: 'order finished',
        MNG_CONSOLE: 'management console',
        ORDER_HAS_BEEN_GENERATED: 'your order has been generated, you can go to the management console to view the order status and use the related resources',
        ORDER_IS_EFFECTIVE_AFTER_APPROVED: 'The order will be taken effective after approval',

        //ts
        SUCCESSFULLY_EMPTY_SHOPPING_CART: 'successfully empty the shopping cart ',
        SURE_TO_EMPTY_EMPTY_SHOPPING_CART: 'are you sure to empty the shopping cart?',
        SUCCESSFULLY_DELETED: 'successfully deleted',
        DELETE_FAILED: 'delete failed',
        CONFIRM_TO_DELETE: 'confirm to delete?',
        PURCHASE_SUCCESS: 'purchase success',
        PURCHASE_FAILED: 'purchase failed',
    },
    IMAGE: {
        AREA_LIST: ' region list',
        IMAGE_ATTRIBUTION: 'image attribution',
        IMAGE_NAME: 'image name',
        ENETR_IMAGE_NAME_TO_SEARCH: ' enter the image search name',
        OPERATING_SYSTEM: 'operating system',
        IMAGE_TYPE: 'image type',
        SIMPLE_SEARCH: 'simple search',
        RESET_OPTIONS: 'reset option',
        CHOOSE: 'select',
        SYSTEM_BITS: 'system bits',
        IMAGE_CAPACITY: 'image capacity',
        FOUNDER: 'founder',
        CREATED_DEPARTMENT: 'create department',
        PROGRESS_RATE: 'progress rate',
        CUSTOM_IMAGE_NAME: 'custom image name',
        CUSTOM_IMAGE_APPLICATION_RANGE: 'custom image application range',
        CUSTOM_IMAGE_DESCRIPTION: 'custom image description',

        //TS
        IMAGE_NAME_CAN_NOT_BE_BLANK: 'image name can not be blank',
        EDIT_IMAGE: 'edit image'

    },
    CLOUD_HOST: {
        FAILED_TO_RETRIEVE_INSTANCE_DETAILS: 'failed to retrieve instance details',
        PLEASE_SELECT_A_SERVICE_DIRECTORY: 'please select a service directory',
        PLEASE_SELECT_ONLY_ONE_SERVICE_DIRECTORY: 'please select only one service directory',
        INSTANCE_STATUS_UPDATE_FAILED: 'instance status update failed',
        FAILED_TO_GET_THE_ORDER_LIST_DATA: 'failed to get the order list data',
        CONFIGURATION_SUBMISSION_FAILED___CONTACT_ADMINISTRATOR: 'configuration application submitted successfully',
        CONFIGURATION_APPLICATION_SUBMITTED_SUCCESSFULLY: 'configuration applications submitted to success',
        LINK_MANAGEMENT_TERMINAL: 'link management terminal',
        INSTANCE_CONFIGURATION_FAMILY: 'instance flavor family',
        REPLACE_SYSTEM_DISK: 'replace system disk',
        BROADBAND_BILLING_MODE: 'broadband billing mode',
        CURRENT_USE_BANDWIDTH: 'current use bandwidth',
        ACCORDING_TO_BROADBAND: 'according to broadband',
        SET_ALARM_RULES: 'set alarm rules',
        SOFT_RESTART: 'soft restart',
        SOFT_OFF: 'soft off',
        HARD_RESTART: 'hard restart',
        HARD_OFF: 'hard off',
        MORE_CREATING: 'more creating',
        CREATE_FROM_IMAGE: 'create from image',
        CREATE_snapshot_IMAGE: ' create from snapshot',
        CREATE_FROM_VOLUME: 'create from volume',
        CREATE_FROM_VOLUME_TEMPLATE: 'create from volume template',
        PURCHASE_QUANTITY: 'purchase quantity',
        PURCHASE_PRICE: 'purchase price',
        ADD_TO_CART: 'add to shopping cart',
        PRICE_LIST: 'price list',
    },
    USER_CENTER:{
        SELECT_THE_AUTHENTICATION_SOURCE_AND_ENTER_THE_QUERY_STRING: 'select the authorization source and enter the query string',
        PLEASE_ENTER_YOUR_ADMINISTRATOR_NAME: "please enter the administrator's name",
        PLEASE_ENTER_A_PHONE: 'please enter the phone number',
        PLEASE_ENTER_A_NAME: 'please enter the name',
        PLEASE_ENTER_A_ACCOUNT: 'please enter the account',
        PLEASE_ENTER_THE_DEPARTMENT_NAME: 'please enter the department name',
        PLEASE_ENTER_THE_DESCRIPTION: 'please enter the description',
        PLEASE_ENTER_A_VALID_PHONE_NUMBER: 'please enter a valid phone number',
        PLEASE_SELECT_A_ADMINISTRATOR_USER: 'please select the AD user',
        SELECT_AT_LEAST_ONE_ROLE: 'select at least one role',
        PLEASE_SELECT_THE_INSTITUTION: 'please select the institution',
        CREATE_MANAGER_ACCOUNT: 'create the AD account ',
        CREAT_A_LOCAL_ACCOUNT: 'create the local account',
        EDIT_MANAGER_ACCOUNT: 'edit AD account',
        EDIT_LOCAL_ACCOUNT: 'edit local account',
        ACCOUNT_STATUS_IS_ENABLED: 'account status is enabled',
        ACCOUNT_STATUS_IS_DISABKED: 'account status is disabled',
        ENABLE_ACCOUNT: 'enable account',
        DISABKE_ACCOUNT: 'disable account',
        DELETE_ACCOUNT: 'delete ACCOUNT',
        YOU_SELECT_ENABLE_PLEASE_CONFIRM: 'you have chosen to enable {{value_1}}, please confirm',
        YOU_SELECT_DISENABLE_PLEASE_CONFIRM_INSTITUTIONAL_MEMBERS_WILL_NOT_BE_ABLE_TO_OPERATE_RELATED_RESOURCES: 'You chose to disable {{value_1}}, please confirm. If confirmed, the Department will be deleted and the user in the Department will be removed',
        UNABLE_TO_DELETE_ENABLED_ACCOUNT: 'Unable to delete enabled account',
        YOU_SELECT_DELETE_USER_WILL_BE_DELETE: 'You have chosen to remove {{value_1}}, please confirm. If confirmed, the Department will be deleted and the user in the Department will be removed',
        THE_ACCOUNT_HAS_BEEN_OCCUPIED:'The account has been taken',
        NAME_CANNOT_BE_EMPTY: 'name cannot be empty',
        PHONE_CANNOT_BE_EMPTY: 'phone cannot be empty',
        ACCOUNT_CANNOT_BE_EMPTY: 'account cannot be empty',
        DEPARTMENT_NAME_CANNOT_BE_EMPTY: 'department name cannot be empty',
        PLEASE_SELECT: 'please select',
        ENTER_ADMINISTRATOR_INFORMATION_SERCH: 'enter AD user search information',
        EMAIL_ADDRESS: 'email address',
        CONTECT_NUMBER: 'contect number',
        BINDING_ROLE: 'binding role',
        BINDING_DEPARTMENT: 'binding department',
        MORE_DEPARTMENT: 'more departments',
        REGISTERED_PLEASE_REENTER_THE_ACCOUNT: 'registered, please re-enter the account',
        ACCOUNT_ERRO_ENTER_EMAIL: 'account format input error, please enter the correct e-mail address',
        PHONE_ERRO_ENTER_PHONE: 'phone number format input error, please enter the correct phone number',
        PHONE_ACC_ERRO_ENTER_PHONE: 'phone number input error, please enter the correct phone number',
        AUTHENTICATION_SOURCE: 'authorization source',
        ENTER_ACCOUNT_INFORMATION_TO_SEARCH_QUICKLY: 'enter the account quick search information',
        ROLE:'role',
        DELETE_DEPARTMENT:'delete department',
        THE_STATE_OF_THE_ORGANIZATION_HAS_BEEN_DISABLED: 'the status of the organization is disabled ',
        DISENABLE_DEPARTMENT: 'disable account',
        CREATE_DEPARTMENT: 'create department',
        YOU_SELECT_DISENABLE_PLEASE_CONFIRM: 'you chose to disable {{value_1}}, please confirm. If confirmed, the member will not be able to operate the relevant resources',
        QUOTA_SETTING: 'quota setting',
        DEPARTMENTAL_QUOTA: 'department quota',
        DEPARTMENT_HAS_USED_THE_AMOUNT: 'department usage',
        ENTERPRISES_CAN_ALLOCATE_THE_AMOUNT: 'enterprise allocation quota ',
        STORAGE_LIMIT: 'storage limit',
        ENTERPRISE_QUOTA_INFORMATION: 'enterprise quota information: maximum quota / available quota',
        NUMBER_OF_DEPARTMENT_PERSONNEL: 'number of department personnel',
        DEPARTMENT_HEAD: 'department head',
        MODIFY_PASSWORD: 'modify password',
        NEW_PASSWORD_HAS_COME_INTO_EFFECT: 'new password is taken effective',
        CURRENT_PASSWORD: 'current password',
        PASSWORD_FORMAT_ERROR: 'password format error',
        NEW_PASSWORD_FORMAT_ERROR: 'new password format error',
        NEW_PASSWORD: 'new password',
        THE_NEW_PASSWORD_CANNOT_BE_THE_SAME_AS_THE_ORIGINAL_PASSWORD: 'the new password cannot be the same as the original password',
        PASSWORD_INPUT_IS_NOT_CONSISTENT: 'password input is not consistent',

    }
}