export const TranslateCN = {
    test: 'abc{{value}}',
    LANG: '中文',
    COMMON: {
        PROMPT: '提示',
        CONFIRM: '确认',
        CANCEL: '取消',
        EXIT: '退出',
        DELETE: '删除',
        RESET: '重置',
        NUMBER: '编号',
        SAVE: '保存',
        ORDER_NUMBER: '订单号',
        ORDER_ID: '订单ID',
        OPERATION: '操作',
        MORE_ACTIONS: '更多操作',
        STATUS: '状态',
        TYPE: '类型',
        DESCRIPTION: '描述',
        ORDERS: '订单',
        ORDER: '订购',
        OVERVIEW: '概览',
        LABEL: '标签',
        EXPENSE: '费用',
        TOTAL_EXPENSE: '总费用',
        ONE_TIME_COSTS: '一次性费用',
        PAYMENT_METHODS: '付费方式',
        TOTAL_COST: '费用总计',
        BILLING_MODE: '计费模式',
        BY_VOLUMN: '按量',
        DETAILS: '详情',
        BUY_NOW: '立即购买',
        SHOPPING_CART: '购物车',
        PURCHASE_AMOUNT: '购买量',
        PURCHASE_DURATION: '购买时长',
        ADD_TO_SHOPPING_CART: '加入购物车',
        CHECK_SHOPPING_CART: '查看购物车',
        EMPTY_SHOPPING_CART: '清空购物车',
        NAME: '名称',
        NONE: '无',
        ALL: '所有',
        DEPARTMENT: '部门',
        PURCHASER: '订购人',
        PRODUCT: '产品',
        PURCHASED: '已购',
        QUANTITY: '数量',
        PRICE: '价格',
        PERMANENCE: '永久',
        MANAGEMENT: '管理',
        INFORMATION: '信息',
        BASIC: '基本',
        ENTERPRISE: '企业',
        DATE: '日期',
        HISTORY: '历史',
        EXPLAIN: '说明',
        USERS: '用户',
        WARNING: '警告',
        PLEASE_WAIT: '请等待',
        ADD: '增加',
        UPDATE: '更新',
        MODIFY: '修改',
        QUERY: '查询',
        PUBLIC: '公',
        PRIVATE: '私',
        LIST: '列表',
        VIEW: '查看',
        EDIT: '编辑',
        CREATE: '创建',
        SEARCH: '搜索',
        SELECT_ALL: '全选',
        SELECT: '选择',
        SPECIFICATION: '规格',
        PHONE: '电话',
        ACCOUNT: '账号',
        TOTAL: '共',
        REMAIN: '剩下',
        LOCAL: '本地',
        PASSWORD: '密码',


        //单位
        $: "￥",
        YUAN: '元',
        GB: 'GB',
        ONE_SET: '1台',
        TWO_SET: '2台',
        THREE_SET: '3台',
        FOUR_SET: '4台',
        FIVE_SET: '5台',
        CORE: '核',

        //状态名词
        ENABLED: '已启用',
        ENABLE: '启用',
        DISENABLED: '禁用',
        NOT_ENABLED: '未启用',
        NOT_APPROVED: '未审批',
        APPROVED: '已审批',
        NEWLY_CREATED: '新创建',
        IN_PROCESS: '处理中',
        COMPLETED: '已完成',
        UNSUBSCRIBE: '退订',
        RENEW: '续订',
        RENEW_DATA_FAILED: '续订失败',
        START: '启动',
        SHUTDOWN: '关机',
        PAUSE: '暂停',
        RESTORE: '恢复',
        HARD_REBOOT: '硬重启',
        SOFT_RESTART: '软重启',
        RUNNING: '运行中',
        PENDING: '挂起',
        DELETED: '已删除',


        //专业术语
        MIRROR: '镜像',
        CLOUD_HOSTING: '云主机',
        CLOUD_HOST_NAME: '云主机名称',
        CLOUD_HARD_DISK: '云硬盘',
        CLOUD_HRAD_DISK_NAME: '云硬盘名称',
        ENTER_CLOUD_HARD_DISK_INFORMATION_TO_SEARCH: '输入云硬盘信息搜索',
        ENTER_CLOUD_HOST_INFORMATION_TO_SEARCH: '输入云主机信息搜索',
        RESET_SEARCH: '重置搜索',
        CLOUD_PLATFORM: '云平台',
        RAM: '内存',
        CONFIGURATION: '配置',
        CURRENT_CONFIGURATION: '当前配置',
        STORAGE: '存储',
        STORAGE_TYPE: '存储类型',
        SNAPSHOT: '快照',
        CONSOLE: '控制台',
        PHYSICAL_MACHINE: '物理机',
        FLOAT: '浮动',
        PATH: '地址',
        SERVICES: '服务',
        INSTANCE: '实例',
        INSTANCE_CONFIGURATION: '实例规格',
        CAPATITY: '容量',
        CAPACITY_GB: '容量(GB)',
        MOUNT: '挂载',
        ZONE: '区域',
        ZONE_DATA_FAILED: '区域加载失败',
        AVAILABLE_ZONE: '可用区',
        AVAILABLE_ZONE_DATA_ERROR: '可用区数据加载错误',
        AREA: '区域',
        REGION_AND_AVAILABLE_AREA: '所在区域及可用区',
        CREATED_TIME: '创建时间',
        EXPIRE_DATE: '到期时间',
        SYSTEM: '系统',
        SYSTEM_PROMPT: '系统提示',
        OPERATOR: '操作者',
        EXECUTOR: '执行者',
        DATA_ACQUISITION_FAILURE: '数据获取失败',
        UPDATE_FAILED: '更新失败',
        NETWORK: '网络',
        CLASSIC: '经典',
        DISK: '磁盘',
        MONITORING: '监控',
        USER_NAME: '用户名',

        //ts
        CLOUD_HOST_OPERATION: '云主机操作',
        SUCCESS: '成功！',
        FAILED: '失败！',
        FAILED_TO_GET_DATA: '获取数据失败！',
        OPERATION_ERROR: '操作错误',
        OPERATION_SUC: '操作成功',

        //长句子
        SET_NAME_FORMAT: '2-68个字符，以大小写字母或中文开头，可包含数字，"."，"-"，"_"'
    },
    SITE: {
        EXIT: '退出',
        MNG_CONSOLE: '管理控制台',
    },
    DIALOG: {
        PROMPT: '提示',
        CONFIRM: '确认',
        CANCEL: '取消',
        COMMIT: '提交',
        SAVE: '保存',
        CLOSE: '关闭'
    },
    MENU: {
        CLOUD_HOSTING_SERVICES: '云主机服务',
        CLOUD_HOSTING_INSTANCE: '云主机实例',
        CLOUD_HARD_DISK: '云硬盘',
        VIRTUAL_MACHINE_INSTANCE: '虚拟机实例',
        MIRROR: '镜像',
        PHYSICAL_SERVERS: '物理机服务',
        ACCOUNT_MANAGEMENT: '账号管理',
        EXPENSE_CENTER: '费用中心',
        LOAD_BALANCER: '负载均衡服务器',
        DEPARTMENT_MANAGENMENT: '部门管理',
        AUTHORITY_MANAGEMENT: '权限管理',
        PRICE_SET: '价格设置',
        QUOTA_MANAGEMENT: '配额管理',
        APPROVAL_CENTER: '审批中心',
        NOT_APPROVED: '未审批',
        APPROVED: '已审批',
        PURCHASED_SERVICE_MANAGEMENT: '已购服务管理',
        ORDER_INQUIRY: '订单查询',
        ACCOUNT_CENTER: '用户中心',
        ORGANIZATION_MANAGEMENT: '组织管理',
        PERSONAL_ACCOUNT_MANAGEMENT: '个人账户管理',
        PRODUCTS_SERVICES: '产品与服务',
        CLOUD_HOSTING: '云主机',
        OVERVIEW: '概览',
        ORDER: '订购',
        INSTANCE_LIST: '实例列表',
        CASE_MNY: '工单管理',
    },
    VM_INSTANCE: {
        CHOOSE_HOST_UN:"请选择要退订的主机",
        ALREADY_STARTED_UN_PROCESS:"已发起退订流程（系统处理需要一定的时间，请勿重复退订）！",
        CLOUD_HOST_DETAILS: '云主机详情',
        RETURNS_THE_CLOUD_HOST_LIST: '返回云主机列表',
        MORE_ACTIONS: '更多操作',
        EDIT_THE_CLOUD_HOST: '编辑云主机',
        DELETE_THE_CLOUD_HOST: '删除云主机',
        CONSOLE: '控制台',
        BASIC_INFORMATION: '基本信息',
        INSTANCE_NAME: '实例名称',
        AVAILABLE_AREA: '所在可用区',
        OPERATION_HOURS: '运行时间',
        STATUS: '状态',
        RESOURCE: '来源',
        EXTRA_INFORMATION: '附加信息',
        EXTRA_SERVICES: '附加服务',
        TYPE: '类型',
        SERVICE_LEVEL: '服务级别',
        LABEL: '标签',
        DESCRIPTION: '描述',
        CONFIGURATION_INFORMATION: '配置信息',
        CPU: 'CPU',
        RAM: '内存',
        MIRROR: '镜像',
        INTERNAL_IP: '内部IP',
        EXTERNA_IP: '外部IP',
        DISK_INFORMATION: '磁盘信息',
        BOOT_DISK: '启动盘',
        DATA_DISK: '数据盘',
        SNAPSHOT: '快照：',
        SECURITY_INFORMATION: '安全信息',
        SECURITY_GROUP: '安全组',
        PAID_INFORMATION: '付费信息',
        ORDER_NUMBER: '订单编号',
        PAYMENT_METHODS: '付费方式',
        CREATED_DATE: '创建时间',
        EXPIRE_DATE: '到期时间',
        RELEASE_DATE: '释放时间',
        HOST_ONE_PRICE: '云主机单价',

        //cloud-host-list
        REGION_LIST: '区域列表',
        CREATE_CLOUD_HOST: '创建云主机',
        UNSUBSCRIBE_CLOUD_HOST: '退订云主机',
        BIND_FLOATING_IP: '绑定浮动IP',
        UNBIND_FLOATING_IP: '解绑浮动IP',
        VIEW_CONSOLE: '查看控制台',
        UNINSTALL_CLOUD_DISK:'卸载云硬盘',
        FORCE_DELETE_CLOUD: '该云硬盘处于挂载状态，是否强制删除?',
        SURE_DELETE_CLOUD: '是否确认删除该云硬盘?',

        //cloud-host-order.html
        NET: '网络',
        NET_TYPE: '网络类型',
        PLEASE_SELECT_SUBNET_YOU_NEED: '请选择您需要的子网网段',
        CONSULT_ADMIN_ABOUT_CHOOSING: '如果您不知道如何选择，请咨询管理员',
        INSTANCE_CONFIGURATION: '实例规格',
        CLOUD_HOST_SOURCE: '云主机源',
        START_SOURCE: '启动源',
        MIRROR_TYPE: '镜像类型',
        MIRROR_LIST: '镜像列表',
        STORE: '存储',
        PASSWORD_SETTING: '密码设置',
        USER_NAME: '用户名',
        LOGIN_PASSWORD: '登录密码',
        PLEASE_ENTER_HOST_PASSWORD: '请输入主机密码',
        CONFIRM_PASSWORD: '确认密码',
        MIRROR_NAME: '镜像名称',
        CLOUD_HOST_COSTS: '云主机费用',
        CLOUD_HARD_DISK_COSTS: '云硬盘费用',
        BY_VOLUMN_COSTS: '按量费用',
        TOTAL_COST: '费用总计',
        BILLINGARR: '周期费用',
        TOTAL_BILLINGARR: '总周期费用',
        BILLINGARR_TEXT: '以上为总费用估算，实际支付金额，请以每月账单为准。',
        ANNUAL_SUBSCRIPTION: '包年包月',
        PRODUCT_ORDER_DESCRIPTION: '不同区域之间的产品内网不互通；订购后不支持更换区域，请谨慎选择！',
        DEFINITION_OF_PUBLIC_IMAGE_AND_CUSTOM_IMAGE: '公共镜像即基础操作系统，自定义镜像为企业根据基础操作系统做过额外配置或优化后的操作系统',
        PASSWORD_COMPLEXITY_DESCRIPTION: '密码复杂度：8-30个字符，且同时包括三项（大写字母，小写字母，数字和特殊符号）',

        //cloud-host-order.ts
        PASSWORD_FORMAT_IS_NOT_CORRECT: '密码格式不正确',
        TWO_PASSWORD_ENTRIES_ARE_INCONSISTENT: '两次密码输入不一致',
        HOST_NAME_FORMAT_IS_NOT_CORRECT: '主机名称格式不正确',
        PURCHASE_DURATION_DESCRIPTION: '请输入购买时长为最大不超过999的数字',
        PLEASE_SELECT_CLOUD_PALTFORM: '请选择云平台',
        PLEASE_SELECT_AVAILABLE_ZONE: '请选择可用区',
        PLEASE_SELECT_CPU: '请选择cpu',
        PLEASE_SELECT_RAM: '请选择内存',
        PLEASE_SELECT_NET_TYPE: '请选择网络类型',
        PLEASE_SELECT_SECURITY_GROUP: '请选择安全组',
        PLEASE_SELECT_STARTUP_SOURCE: '请选择启动源',
        PLEASE_SELECT_IMAGE_TYPE: '请选择镜像类型',
        PLEASE_SELECT_IMAGE_NAME: '请选择镜像名称',
        PLEASE_SELECT_TIMELINE_UNIT: '请选择时长类型',


        //sub-add-storage
        ADD_DATA_DISK: '增加数据盘',
        ADD_HEAD: '一共可以增加',
        ADD_MIDDLE: '块，还可以增加',
        ADD_TAIL: '块',

        PHYSICAL_MACHINE_ORDER: '物理机订购',
        SELECT_PHYSICAL_RES: '选择物理资源',
        SELECT_FROM_POOL: '从物理资源池中选取',
        SYSTEM_AUTO_IN: '如不填写，则系统自动生成',
        ENTER_PASSWORD_AGAIN: '请再次输入主机密码',
        ORDER_CLOUD_HOSTING: '订购云主机',
        UNSUBSRIBE_ALL_DISK: '是否要一起退订所有云硬盘，挂载它们的云主机为',

    },
    ORDER_MNG: {//_DATA_FAILED
        ORDER_DETAILS: '订购详情',
        ORDERS_DETAILS: '订单详情',
        ORDERS_DETAILS_DATA_FAILED: '订单详情加载失败',
        RENEWAL_FEE: '续订费用',
        RENEWAL_FEE_DATA_FAILED: '续订费用加载失败',
        DEPARTMENT_LIST: '部门列表',
        DEPARTMENT_LIST_DATA_FAILED: '部门列表加载失败',
        SUBSCRIBER_LIST: '订购人列表',
        SUBSCRIBER_LIST_DATA_FAILED: '订购人列表加载失败',
        SUBMITTER_LIST: '提交者列表',
        ORDERS_LIST: '订单列表',
        ORDERED_LIST: '已订购列表',
        ORDERED_LIST_DATA_FAILED: '已订购列表加载失败',
        ONLY_SUCCESS_OR_EXPIRING_ORDERS_CAN_BE_RENEWED: '只有“成功”或“即将过期”的订单可以续订',
        ONLY_SUCCESS_OR_EXPIRING_ORDERS_CAN_BE_UNSUBSCRIBE: '只有“已激活”的订单可以退订',
        PURCHASE_TIME: '购买时长',
        PLEASE_ENTER_A_NUMBER_QUERY: '请输入编号查询',
        DUE_DATE: '到期时间',
        THE_CURRENT_QUERY_TO: '当前查询到',
        PURCHASED_SERVICE_PURCHASED_SERVICE_ARE_LISTED_BELOW: '个已购服务，已购服务列表如下',
        CHARGING_MODE: '计费模式',
        PURCHASE_CYCLE: '购买周期',
        RENEWAL_EXPIRATION_TIME: '续订后到期时间',
        YOUR_ORDER_HAS_BEEN_RENEWED___AND_THE_ASSOCIATED_RESOURCES: '你的订单续订已完成，可以进入管理控制台查看订单状态及使用相关资源',
        FOR_APPROVAL___TO_TAKE_EFFECT: '如需审批，则需要订单审批通过后，才能正式生效',
        UNSUBSCRIBE_FROM___HARD_DRIVE: '一起退订该云主机挂载的云硬盘',
        UNSUBSCRIBE_FROM___NO_DRIVE: '你确认要退订该云主机吗',
        WHETHER_TO_CONFIRM___EXIT_THE_PROCESS: '是否确认删除该云硬盘. 如果选"确认", 则卸载该云硬盘并删除. 如果选"取消", 则退出流程',
        WHETHER_TO_CONFIRM_FORCE___EXIT_THE_PROCESS: '是否强制删除. 如果选"确认", 则卸载该云硬盘并删除。 如果选"取消", 则退出流程',
        UNIT_PRICE: '单价费用',
        ASSOCIATED_LIST_OF_SUBSCRIBED_SERVICES: '关联的已订购服务列表',
        ORIGINAL_EXPIRATION_TIME: '原到期时间',
        CONFIRM: '确定',
        ORDER_TRACKING: '订单查询',
        PLEASE_ENTER_THE_ORDER_NUMBER_FUZZY_QUERY: '请输入订单编号模糊查询',
        RESET: '重置',
        ORDER_STATUS: '订单状态',
        ALL_STATUS: '所有状态',
        PRODUCT_TYPE: '产品类型',
        ALL_TYPES: '所有类型',
        CURRENT_QUERY_TO: '当前查询到',
        ORDER_ORDER_LIST_IS_AS_FOLLOWS: '订单，订单列表如下：',
        NUMBER: '编号',
        ORDER_NUMBER: '订单编号',
        ORDER_TYPE: '订单类型',
        EXPENSE: '费用',
        SUBMISSION_TIME: '提交时间',
        COMPLETION_TIME: '完成时间',
        SUBMITTER: '提交者',
        DEPARTMENT: '所属部门',
        OPERATION: '操作',
        NONRECURRING_EXPENSE: '一次性费用',
        EXPENSE_$: '费用',
        DETAILS: '详 情',
        ORDER_NUMBER_: '订单号：',

        MOUNT_CLOUD_HOST_NAME: '挂载云主机名称',
        CANCELLATION_FAILED: '撤单失败',
        ALL_PURCHASER: '所有订购人',
        ALL_ZONE: '所有区',
        ALL_AVAILABLE_ZONE: '所有可用区',
        PURCHASED_SERVICES_DETAILS: '已购买服务详情',
        PURCHASED_SERVICES_NUMBER: '已购买服务编号',
        ORDERS_RENEW: '订单续订',
        ORDERS_UNSUBSCRIBE: '订单退订',
        HISTORY_INFORMATION: '历史信息',
        INSTANCE_TYPE: '实例类型',
        ALL_USERS: '所有用户',
        CANCEL_THE_ORDER:'撤销订单',
        ORDER_INFORMATION: '订单信息',
        ORDER_HISTORY: '订单历史',
    },
    ORG_MNG_LIST: {
        OPERATION_ERROR: '操作错误',
        ORGANIZATIONAL_STATUS_IS_ENABLED: '组织状态已启用',
        ENABLE_DEPARTMENT: '启用部门',
        YOU_CHOOSE_TO_ENABLE_VALUE_PLEASE_CONFIRM: '您选择启用{{value_1}}，请确认',
        EDIT_DEPARTMENT: '编辑部门',
        YOU_CAN_NOT_DELETE_ORGANIZATIONS_THAT_ARE_ENABLED: '不能删除启用状态下的组织'
    },
    MNG_CONSOLE: {
        OVERVIEW_OF_MANAGEMENT_CONTROL: '管理控制概览',
        PURCHASED_SERVICE: '已购买服务',
        WORK_ORDER_STATISTICS: '工单统计',
        TOTAL_QUOTA_USAGE: '部门配额使用率',
        DEPARTMENT_RESOURCES: '部门资源'
    },
    CHECK_CENTER: {
        //check-mng-list.html
        PENDING_LIST: '待审批列表',
        ENTER_THE_ORDER_NUMBER_OR_DEPARTMENT_FOR_QUICK_INQUIRY: '输入订单号或部门快速查询',
        ADVANCED_SEARCH: '高级查询',
        ORDER_ATTRIBUTION: '订单归属',
        ALL_DEPARTMENTS: '所有部门',
        SUBMITTER: '提交者',
        ALL_SUBMITTERS: '所有提交者',
        ORDER_TYPE: '订单类型',
        ALL_TYPES: '所有类型',
        PRODUCT_TYPE: '产品类型',
        QUERY: '查  询',
        RESET: '重置',
        CURRENT_QUERY_IS: '当前查询到',
        THE_QUERY_RESULTS_OF_PENDING_ORDERS: '个订单需要审批，查询结果如下',

        ORDER_DESCRIPTION: '订单描述',
        DEPARTMENT: '部门',
        ENTERPRISE: '企业',
        COST: '费用',
        APPROVAL_RESULTS: '审批结果',
        BILLING_MODE: '计费模式',
        ORDER_CYCLE: '订单周期',
        ONE_TIME_COSTS: '一次性费用',
        AGREE: '同意',
        REFUSE: '拒绝',
        AGREE_REFUSE:'同意/拒绝',
        THE_ORDER_REQUEST_WAS_REJECTED: '订单请求被拒绝',
        REASON: '原因',
        INPUT_CHINESE_OR_CHARACTERS_NOT_MORE_THAN_200_WORDS: '可以输入中文字符,最大不能超过200个字',

        //check-mng-list.ts
        DEPARTMENTS_LIST: '部门列表',
        SUBMITTERS_LIST: '提交者列表',
        SYSTEM: '系统',
        REFUSE_REASON_DESCRIPTION: '必须填写拒绝原因，且不能超出200字',
        APPROVAL_CONSENT: '审批同意',
        CONFIRM_TO_APPROVE_THE_ORDER: '你确认要审批同意该订单吗？',

        //check-mng-hascheck.html
        APPROVED_LIST: '已审批列表',
        APPROVER: '审批人',
        ALL_APPROVERS: '所有审批人',
        APPROVAL_TIME: '审批时间',
        APPROVAL_COMMENTS: '审批意见',

        //check-mng-set
        APPROVAL_SETTINGS: '审批设置',
        IS_APPROVAL_REQUIRED: '是否需要审批?',
        OPEN: '开启',
        CLOSE: '关闭',
        MINUTE: '分钟',
        AUTO_APPROVAL_TIME_SET: '自动审批时间设置',
        EDIT: '编 辑',
        SAVE: '保 存'

    },

    //cloud-drive文件夹下
    CLOUD_DRIVE_LIST: {
        AREA_LIST: '区域列表',
        ADVANCED_SEARCH: '高级搜索',
        CREATE_CLOUD_HRAD_DISK: '创建云硬盘',
        CLOUD_HRAD_DISK_NAME: '云硬盘名称',
        MOUNT_LOCATION_CLOUD_HOST_NAME: '挂载位置（云主机名称）',
        AVAILABLE_AREA: "所在可用区",
        UNSUBSCRIBE_DISK: '退订云硬盘',
        UNSUBSCRIBE_PROCESS:'已发起退订流程（系统处理需要一定的时间，请勿重复退订）！',

        REGION: '所在地区',
        ATTRIBUTE: '属性',
        OPERATE: '操作',
        MOUNT: '挂载',
        UNINSTALL: '卸载',
        MOUNT_CLOUD_HOST: '挂载云主机',
        CLOUD_DISK_OPERATION: '云硬盘操作',

    },
    CLOUD_DRIVE_ORDER: {

        CLOUD_HARD_DISK_ORDER_DESCRIPTION: '云硬盘只能挂载到同一可用区下的云主机实例，订购成功后不支持更换云硬盘的区域和可用区；请谨慎选择',
        CONFIGURATION_OPTIONS: '配置选项',
        BLANK_DISK: '空白盘',
        CLOUD_HARD_DISK_TYPE: '云硬盘类型',
        //73行
        CLOUD_HARD_DISK_INSTANCE_NAME: '云硬盘实例名称',
        //81行
        WHETHER_TO_AMOUNT_ON_CLOUD_HOST: '是否挂载到云主机',
        CLOUD_HOST_INSTANCE_LIST: '云主机实例列表',
        CLOUD_HRAD_DISK_TYPE: '云硬盘类型',
        MOUNT_TO_CLOUD_HOST: '挂载到云主机',
        BUY_HEAD: '可以购买容量',
        BUY_MID_FIRST: 'GB的云硬盘。',
        BUY_MID_SECOND: 'GB起，增加按照每',
        BUY_TAIL: 'GB一档。',
        ORDER_TEXT: '云硬盘产品将根据您购买的容量按周期计费，实际支付金额，请以每月账单为准。',

        //TS
        SUCCESSFULLY_ADDED_TO_SHOPPING_CART: '加入购物车成功!',
        PLEASE_SELECT_CLOUD_PLATFORM: '请选择云平台',
        PLEASE_SELECT_AVAILABLE_ZONE: '请选择可用区',
        PLEASE_SELECT_CLOUD_HARD_DISK: '请选择云硬盘',
        PLEASE_SELECT_CLOUD_HARD_DISK_TYPE: '请选择云硬盘类型',
        CLOUD_HARD_DISK_NAME_FORMAT_IS_NOT_CORRECT: '云硬盘名称格式不正确',
        SKU_IS_NOT_CORRECT: 'sku不正确'
    },
    SUB_TABLE_LIST: {
        BACKUP_NAME: '备份名称',
        SOURCE_CLOUD_HARD_DISK_NAME: '源云硬盘名称',
        SOURCE_VIRTUAL_MACHINE_NAME: '源虚拟机名称',
        ENTER_INFORMATION_TO_SEARCH: '输入信息搜索',
        INTERNAL_IP: '内部IP',
        EXTERNAL_IP: '外部IP'
    },
    OS_DISK: {
        //os-disk-list.ts  and  os-disk-order.ts
        CLOUD_HARD_DISK_LIST: '云硬盘列表',
        ORDER_CLOUD_HARD_DISK: '订购云硬盘'
    },
    VM_DISK: {
        //vw-disk-list.ts  and  vw-disk-order.ts
        VMWARE_CLOUD_HARD_DISK_LIST: 'VMware云硬盘列表',
        VMWARE_CLOUD_HOSTING_LIST: 'VMware云主机列表',
        ORDER_VMWARE_CLOUD_HARD_DISK: '订购VMware云硬盘',
        ORDER_VMWARE_CLOUD_HOSTING: '订购VMware云主机'
    },
    //shopping-cart文件夹下
    SHOPPING_CART: {
        //cart-list.html
        PRODUCT_INFORMATION: '产品信息',
        PRODUCT_TYPE: '产品类型',
        PURCHASE_CYCLE: '购买周期',
        CHARGE_DETAIL: '费用明细',
        QUANTITY: '数量',
        NOTE: '小计',
        BASICPRICE : '基础周期费用',
        UNITARR: "按量费用",
        BILLINGARR: "周期费用",
        REMOVE_FROM_CART: '从购物车中移除',
        INCREMENTAL_CYCLE_COST: '增量周期费用',
        UNIT_PRICE: '单价费用',
        SET: '台',
        BACK_TO_PRODUCT_PURCHASE: '<返回产品购买',
        SETTLE_ACCOUNTS: '下单结算',
        TOTAL_COST: '( 费用合计 )',

        //cart-order.html
        ORDER_FINISHED: '订单完成',
        MNG_CONSOLE: '管理控制台',
        ORDER_HAS_BEEN_GENERATED: '您的订单已生成，可以进入管理控制台查看订单状态及使用相关资源',
        ORDER_IS_EFFECTIVE_AFTER_APPROVED: '如需审批，则需要订单审批通过后，才能正式生效。',

        //ts
        SUCCESSFULLY_EMPTY_SHOPPING_CART: '清空购物车成功!',
        SURE_TO_EMPTY_EMPTY_SHOPPING_CART: '你确定要清空购物车吗？',
        SUCCESSFULLY_DELETED: '删除成功!',
        DELETE_FAILED: '删除失败',
        CONFIRM_TO_DELETE: '你确定要删除吗？',
        PURCHASE_SUCCESS: '购买成功！',
        PURCHASE_FAILED: '购买失败',
    },
    IMAGE: {
        AREA_LIST: '区域列表',
        IMAGE_ATTRIBUTION: '镜像归属',
        IMAGE_NAME: '镜像名称',
        ENETR_IMAGE_NAME_TO_SEARCH: '输入镜像名称搜索',
        OPERATING_SYSTEM: '操作系统',
        IMAGE_TYPE: '镜像类型',
        SIMPLE_SEARCH: '简单搜索',
        RESET_OPTIONS: '重置选项',
        CHOOSE: '选择',
        SYSTEM_BITS: '系统位数',
        IMAGE_CAPACITY: '镜像容量',
        FOUNDER: '创建人',
        CREATED_DEPARTMENT: '创建部门',
        PROGRESS_RATE: '进度',
        CUSTOM_IMAGE_NAME: '自定义镜像名',
        CUSTOM_IMAGE_APPLICATION_RANGE: '自定义镜像应用范围',
        CUSTOM_IMAGE_DESCRIPTION: '自定义镜像描述',
        CONFIRM_DELETE_VALUE:'确认删除{{value_1}}?',

        //TS
        IMAGE_NAME_CAN_NOT_BE_BLANK: '镜像名称不能为空',
        EDIT_IMAGE: '编辑镜像'

    },
    CLOUD_HOST: {
        CLOUD_HOST_LIST:"云主机列表",
        FAILED_TO_RETRIEVE_INSTANCE_DETAILS: '实例详细信息获取失败。',
        PLEASE_SELECT_A_SERVICE_DIRECTORY: '请选择一个服务目录',
        PLEASE_SELECT_ONLY_ONE_SERVICE_DIRECTORY: '请只选择一个服务目录',
        INSTANCE_STATUS_UPDATE_FAILED: '实例状态更新失败。',
        FAILED_TO_GET_THE_ORDER_LIST_DATA: '可订购列表数据获取失败。',
        CONFIGURATION_SUBMISSION_FAILED___CONTACT_ADMINISTRATOR: '配置申请提交失败，请重新尝试或者联络管理员',
        CONFIGURATION_APPLICATION_SUBMITTED_SUCCESSFULLY: '配置申请提交成功',
        LINK_MANAGEMENT_TERMINAL: '链接管理终端',
        INSTANCE_CONFIGURATION_FAMILY: '实例规格族',
        REPLACE_SYSTEM_DISK: '更换系统盘',
        BROADBAND_BILLING_MODE: '宽带计费方式',
        CURRENT_USE_BANDWIDTH: '当前使用带宽',
        ACCORDING_TO_BROADBAND: '按宽带',
        SET_ALARM_RULES: '设置报警规则',
        SOFT_RESTART: '软重启',
        SOFT_OFF: '软关机',
        HARD_RESTART: '硬重启',
        HARD_OFF: '硬关机',
        MORE_CREATING: '更多创建',
        CREATE_FROM_IMAGE: '从镜像创建',
        CREATE_snapshot_IMAGE: '从快照创建',
        CREATE_FROM_VOLUME: '从卷创建',
        CREATE_FROM_VOLUME_TEMPLATE: '从卷模板创建',
        PURCHASE_QUANTITY: '购买数量',
        PURCHASE_PRICE: '预购价',
        ADD_TO_CART: '加入购物车',
        PRICE_LIST: '价格表',
        GET_NETWORK_FAILURE: '获取网络失败',
        GET_IMAGE_FAILURE: '获取镜像失败',

        INSTANCE_DETAILS: '实例详情',
        PUBLIC_NETWORK: '公网',
        PRIVATE_NETWORK: '私网',
        CLASSIC_NETWORK: '经典网络',
        MONITORING_INFO: '监控信息',
        VIEW_DETAILS: '查看详情',
        CREATE_SNAPSHOT: '创建快照',
    },
    USER_CENTER:{
        SELECT_THE_AUTHENTICATION_SOURCE_AND_ENTER_THE_QUERY_STRING: '请选择认证源并且输入查询字符串',
        PLEASE_ENTER_YOUR_ADMINISTRATOR_NAME: '请输入管理员姓名',
        PLEASE_ENTER_A_PHONE: '请输入电话',
        PLEASE_ENTER_A_NAME: '请输入姓名',
        PLEASE_ENTER_A_ACCOUNT: '请输入账号',
        PLEASE_ENTER_THE_DEPARTMENT_NAME: '请输入部门名称',
        PLEASE_ENTER_THE_DESCRIPTION: '请输入描述',
        PLEASE_ENTER_A_VALID_PHONE_NUMBER: '请输入合法的联系电话',
        PLEASE_SELECT_A_ADMINISTRATOR_USER: '请选择AD用户',
        SELECT_AT_LEAST_ONE_ROLE: '至少选择一个角色',
        PLEASE_SELECT_THE_INSTITUTION: '请选择所属机构',
        CREATE_MANAGER_ACCOUNT: '创建AD账号',
        CREAT_A_LOCAL_ACCOUNT: '创建本地账号',
        EDIT_MANAGER_ACCOUNT: '编辑AD账号',
        EDIT_LOCAL_ACCOUNT: '编辑本地账号',
        ACCOUNT_STATUS_IS_ENABLED: '账号状态已启用',
        ACCOUNT_STATUS_IS_DISABKED: '账号状态已禁用',
        ENABLE_ACCOUNT: '启用帐号',
        DISABKE_ACCOUNT: '禁用帐号',
        DELETE_ACCOUNT: '删除帐号',
        YOU_SELECT_ENABLE_PLEASE_CONFIRM: '您选择启用{{value_1}}，请确认',
        YOU_SELECT_DISENABLE_PLEASE_CONFIRM_INSTITUTIONAL_MEMBERS_WILL_NOT_BE_ABLE_TO_OPERATE_RELATED_RESOURCES: '您选择禁用{{value_1}}，请确认。如果确认，部门将被删除且该部门中的用户将被移除。',
        UNABLE_TO_DELETE_ENABLED_ACCOUNT: '不能删除启用状态下的账号',
        YOU_SELECT_DELETE_USER_WILL_BE_DELETE: '您选择删除{{value_1}}，请确认。如果确认，部门将被删除且该部门中的用户将被移除。',
        THE_ACCOUNT_HAS_BEEN_OCCUPIED:'该账户已经被占用',
        NAME_CANNOT_BE_EMPTY: '姓名不能为空',
        PHONE_CANNOT_BE_EMPTY: '电话不能为空',
        ACCOUNT_CANNOT_BE_EMPTY: '账号不能为空',
        DEPARTMENT_NAME_CANNOT_BE_EMPTY: '部门名称不能为空',
        PLEASE_SELECT: '请选择',
        ENTER_ADMINISTRATOR_INFORMATION_SERCH: '输入AD用户信息搜索',
        EMAIL_ADDRESS: '邮箱地址',
        CONTECT_NUMBER: '联系电话',
        BINDING_ROLE: '绑定角色',
        BINDING_DEPARTMENT: '绑定部门',
        MORE_DEPARTMENT: '更多部门',
        REGISTERED_PLEASE_REENTER_THE_ACCOUNT: '已注册，请重新输入账号',
        ACCOUNT_ERRO_ENTER_EMAIL: '账号格式输入错误，请输入正确邮箱地址',
        PHONE_ERRO_ENTER_PHONE: '手机号格式输入错误，请输入正确手机号',
        PHONE_ACC_ERRO_ENTER_PHONE: '手机号码输入错误,请输入正确的手机号',
        AUTHENTICATION_SOURCE: '认证源',
        ENTER_ACCOUNT_INFORMATION_TO_SEARCH_QUICKLY: '输入帐号信息快速搜索',
        ROLE:'角色',
        DELETE_DEPARTMENT:'删除部门',
        THE_STATE_OF_THE_ORGANIZATION_HAS_BEEN_DISABLED: '该组织状态已禁用',
        DISENABLE_DEPARTMENT: '禁用帐号',
        CREATE_DEPARTMENT: '创建帐号',
        YOU_SELECT_DISENABLE_PLEASE_CONFIRM: '您选择禁用{{value_1}}，请确认。如果确认，机构成员将无法操作相关资源',
        QUOTA_SETTING: '配额设置',
        DEPARTMENTAL_QUOTA: '部门配置',
        DEPARTMENT_HAS_USED_THE_AMOUNT: '部门已使用额度',
        ENTERPRISES_CAN_ALLOCATE_THE_AMOUNT: '企业可分配额度',
        STORAGE_LIMIT: '存储额度',
        ENTERPRISE_QUOTA_INFORMATION: '企业配额信息：最大配额/可用额度',
        NUMBER_OF_DEPARTMENT_PERSONNEL: '部门人员数量',
        DEPARTMENT_HEAD: '部门负责人',
        MODIFY_PASSWORD: '修改密码',
        NEW_PASSWORD_HAS_COME_INTO_EFFECT: '新密码已生效',
        CURRENT_PASSWORD: '当前密码',
        PASSWORD_FORMAT_ERROR: '密码格式错误',
        NEW_PASSWORD_FORMAT_ERROR: '新密码格式错误',
        NEW_PASSWORD: '新密码',
        THE_NEW_PASSWORD_CANNOT_BE_THE_SAME_AS_THE_ORIGINAL_PASSWORD: '新密码不能与原密码相同',
        PASSWORD_INPUT_IS_NOT_CONSISTENT: '密码输入不一致',

        RAM_QUANTITY: '内存数量',
        PHYSICAL_QUANTITY: '物理机数量',
        SNAPSHOT_QUANTITY: '快照数量',
        MIRROR_QUANTITY: '镜像数量',
        DEPARTMENT_NAME: '部门名称',
        CONFIRM_NEW_PASSWORD: '确认新密码',

        //msg-mng
        MSG_NOTIFICATION: '消息通知',
        MORE_MSG: '更多消息',

        MSG_CENTER: '消息中心',
        ALL_MSG: '所有消息',
        UNREAD_MSG: '未读消息',
        READ_MSG: '已读消息',
        MARK_READ: '标示已读',
        MSG_CONTENT: '消息内容',
        CREATE_TIME: '创建时间',
        ALL_SELECTED: '全选',

        PLEASE_CHOOSE_MSG: '请选择消息',
        PLEASE_CHOOSE_UNREAD_MSG: '请选择未读消息',

        DELETE_MSG_FAILED: '删除消息失败',
        DELETE_MSG_EXCEPTION: '删除消息异常',

        MARK_MSG_READ_FAILED: '标示消息已读失败',
        MARK_MSG_READ_EXCEPTION: '标示消息已读异常',

        DELETE_MSG_CONFIRM: '您选择删除{{value_1}}条消息，请确认',
        DELETE_MSG: '删除消息',


        //case-mng
        CASE_MNY: '工单管理',
        QUICKSEARCH_BYCASE: '输入工单信息快速搜索',
        TYPE: '类别',
        STATUS: '状态',
        EMERGENCY: '紧急程度',
        CASE_ID: '工单号',
        SUBJECT: '主题',
        CONTACTOR: '联系人',
        CONTACNO: '联系电话',
        SUBMITOR: '提交者',
        SUBMIT_TIME: '提交时间',
        UPDATE_TIME: '更新时间',
        OPERATION: '操作',
        CREATE_CASE: '创建工单',
        DEPARTMENT_OWNED: '所属部门',
        ENTERPRISE_OWNED: '所属企业',
        DESCRIPTION: '描述',
        BASIC_INFO: '基本信息',
        HANDLED_INFO: '处理信息',
        CLOSED_INFO: '关闭信息',
        HANDLER_NAME: '处理人',
        HANDLER_TIME: '处理时间',
        HANDLER_PROCESS: '处理记录',
        CLOSED_TYPE: '关闭类型',
        CLOSED_NAME: '关闭人',
        CLOSED_TIME: '关闭时间',
        TYPE_ALL: '所有类别',
        STATUS_ALL: '所有类别',
        ALL: '所有',
        SELECT: '请选择',
        LIMIT_DESCRIPTION_ONE: '最多只能输入50个文字',
        LIMIT_DESCRIPTION_TWO: '最多只能输入1000个文字',
        CLOSED_ALEARDY: '已关闭',
        EDIT_CASE: '编辑工单',
        DELETE_CASE: '删除工单',
        EDIT_CONTOR: '只有新建状态下，才能编辑工单',
        DELETE_CONTOR: '只有新建状态下，才能删除工单',
        DELETE_CASE_WARNING: '您选择删除{{value_1}}-{{value_2}}工单，请确认。',
        CASE_DETAIL: '工单详细：{{value_1}}-{{value_2}}'

    }
}
