export const TranslateEN = {
    LANG: 'English',
    SITE: {
        EXIT: 'exit'
    }
    ,DIALOG: {
        PROMPT: 'Prompt',
        CONFIRM: 'Confirm',
        CANCEL: 'Cancel'
    },
    MENU: {
        CLOUD_HOSTING_SERVICES: 'Cloud hosting services',
        CLOUD_HOSTING_INSTANCE: 'Cloud hosting instance',
        CLOUD_HARD_DISK: 'Cloud hard disk',
        VIRTUAL_MACHINE_INSTANCE: 'Virtual machine instance',
        MIRROR: 'Mirror',
        PHYSICAL_SERVERS: 'Physical servers',
        ACCOUNT_MANAGEMENT: 'account management',
        EXPENSE_CENTER: 'Expense center',
        LOAD_BALANCER: 'Load balancer',
        DEPARTMENT_MANAGENMENT: 'Department management',
        AUTHORITY_MANAGEMENT: 'Authority management',
        PRICE_SET: 'Price set',
        QUOTA_MANAGEMENT: 'Quota management',
        APPROVAL_CENTER: 'Approval center',
        NOT_APPROVED: 'Not approved',
        APPROVED: 'Approved',
        PURCHASED_SERVICE_MANAGEMENT: 'Purchased service management',
        ORDER_INQUIRY: 'Order inquiry',
        ACCOUNT_CENTER: 'Account center',
        ORGANIZATION_MANAGENMENT: 'Organization management',
        PERSONAL_ACCOUNT_MANAGEMENT: 'Personal account management',
        PRODUCTS_SERVICES: 'Products and services',
        CLOUD_HOSTING: 'Cloud hosting',
        OVERVIEW: 'Overview',
        ORDER: 'Order',
        INSTANCE_LIST: 'Instance list'
    },
    VM_INSTANCE: {
        CLOUD_HOST_DETAILS: 'cloud host details',
        RETURNS_THE_CLOUD_HOST_LIST: 'returns the cloud host list',
        MORE_ACTIONS: 'more actions',
        EDIT_THE_CLOUD_HOST: 'edit the cloud host',
        DELETE_THE_CLOUD_HOST: 'delete the cloud host',
        CONSOLE: 'console',
        BASIC_INFORMATION: 'basic Information',
        INSTANCE_NAME: 'instance name:',
        AVAILABLE_AREA: 'available area:',
        OPERATION_HOURS: 'operation hours:',
        STATUS: 'status:',
        RESOURCE: 'resource:',
        EXTRA_INFORMATION: 'extra information',
        EXTRA_SERVICES: 'extra services:',
        TYPE: 'type:',
        SERVICE_LEVEL: 'service level:',
        LABEL: 'label:',
        DESCRIPTION: 'description:',
        CONFIGURATION_INFORMATION: 'configuration information',
        CPU: 'CPU:',
        RAM: 'RAM:',
        MIRROR: 'Mirror:',
        INTERNAL_IP: 'internal ip:',
        EXTERNA_IP: 'externa ip:',
        DISK_INFORMATION: 'disk information',
        STARTUP_DISK: 'startup disk:',
        DATA_DISK: 'data disk:',
        SNAPSHOT: 'snapshot:',
        SECURITY_INFORMATION: 'security information',
        SECURITY_GROUP: 'security group:',
        PAID_INFORMATION: 'paid information',
        ORDER_NUMBER: 'order number:',
        PAYMENT_METHODS: 'payment methods:',
        CREATED_DATE: 'created date:',
        EXPIRE_DATE: 'Expire date:',
        RELEASE_DATE: 'release date:',
    },
    ORDER_MNG_SEARCH: {
        CONFIRM: 'confirm',
        ORDER_TRACKING: 'Order Tracking',
        PLEASE_ENTER_THE_ORDER_NUMBER_FUZZY_QUERY: 'Please enter the order number fuzzy query',
        RESET: 'Reset',
        ORDER_STATUS: 'order status:',
        ALL_STATUS: 'all status',
        PRODUCT_TYPE: 'product type:',
        ALL_TYPES: 'all types',
        CURRENT_QUERY_TO: 'Current query to',
        ORDER_ORDER_LIST_IS_AS_FOLLOWS: 'order, order list is as follows:',
        NUMBER: 'number',
        ORDER_NUMBER: 'order number',
        ORDER_TYPE: 'order type',
        EXPENSE: 'expense',
        SUBMISSION_TIME: 'submission time',
        COMPLETION_TIME: 'completion time',
        SUBMITTER: 'submitter',
        DEPARTMENT: 'department',
        OPERATION: 'operation',
        NONRECURRING_EXPENSE: 'nonrecurring expense: $',
        EXPENSE_$: 'expense: $',
        DETAILS: 'details',
        ORDER_NUMBER_: 'ORDER_NUMBER:'
    },
    ORG_MNG_LIST: {
        OPERATION_ERROR: 'Opeartion error',
        ORGANIZATIONAL_STATUS_IS_ENABLED: 'Organizational status is enabled',
        ENABLE_DEPARTMENT: 'enable department',
        YOU_CHOOSE_TO_ENABLE_VALUE_PLEASE_CONFIRM: 'You choose to enable {{value}},please confirm',
        EDIT_DEPARTMENT: 'edit department',
        YOU_CAN_NOT_DELETE_ORGANIZATIONS_THAT_ARE_ENABLED: 'You can not delete organizations that are enabled'
    }
}