export class EntResource {
    // authMode: 0
    "cpuQuota": number;
    "dbQuota": number;
    "diskQuota": number;
    "enterpriseId": string;
    "floatIpQuota": number;
    "imageQuota": number;
    "memQuota": number;
    "networkQuota": number;
    "physicalMachineQuota": number;
    "snapshotQuota": number;
    "storageQuota": number;
    "usedCpuQuota": number;
    "usedCpuRate": number;
    "usedDbQuota": number;
    "usedDbRate": number;
    "usedDiskQuota": number;
    "usedDiskRate": number;
    "usedFloatIpQuota": number;
    "usedFloatIpRate": number;
    "usedImageQuota": number;
    "usedImageRate": number;
    "usedMemQuota": number;
    "usedMemRate": number;
    "usedNetworkQuota": number;
    "usedNetworkRate": number;
    "usedPhysicalMachineQuota": number;
    "usedPhysicalMachineRate": number;
    "usedSnapshotQuota": number;
    "usedSnapshotRate": number;
    "usedStorageQuota": number;
    "usedStorageRate": number;
    "usedVmQuota": number;
    "usedVmRate": number;
    "vmQuota": number;
    constructor() {
        this.cpuQuota = 0;
        this.dbQuota = 0;
        this.diskQuota = 0;
        this.floatIpQuota = 0;
        this.imageQuota = 0;
        this.memQuota = 0;
        this.networkQuota = 0;
        this.physicalMachineQuota = 0;
        this.snapshotQuota = 0;
        this.storageQuota = 0;
        this.usedCpuQuota = 0;
        this.usedCpuRate = 0;
        this.usedDbQuota = 0;
        this.usedDbRate = 0;
        this.usedDiskQuota = 0;
        this.usedDiskRate = 0;
        this.usedFloatIpQuota = 0;
        this.usedFloatIpRate = 0;
        this.usedImageQuota = 0;
        this.usedImageRate = 0;
        this.usedMemQuota = 0;
        this.usedMemRate = 0;
        this.usedNetworkQuota = 0;
        this.usedNetworkRate = 0;
        this.usedPhysicalMachineQuota = 0;
        this.usedPhysicalMachineRate = 0;
        this.usedSnapshotQuota = 0;
        this.usedSnapshotRate = 0;
        this.usedStorageQuota = 0;
        this.usedStorageRate = 0;
        this.usedVmQuota = 0;
        this.usedVmRate = 0;
        this.vmQuota = 0;
    }

}