export class EntResource {
    // authMode: 0
    "cpuQuota": number;
    "dbQuota": number;
    "diskQuota": number;
    "enterpriseId": string;
    "floatIpQuota": number;
    "imageQuota": number;
    "memQuota": number;
    "networkQuota": number;
    "physicalMachineQuota": number;
    "snapshotQuota": number;
    "storageQuota": number;
    "usedCpuQuota": number;
    "usedCpuRate":string;
    "usedDbQuota": number;
    "usedDbRate":string;
    "usedDiskQuota": number;
    "usedDiskRate":string;
    "usedFloatIpQuota": number;
    "usedFloatIpRate":string;
    "usedImageQuota": number;
    "usedImageRate":string;
    "usedMemQuota": number;
    "usedMemRate":string;
    "usedNetworkQuota": number;
    "usedNetworkRate":string;
    "usedPhysicalMachineQuota": number;
    "usedPhysicalMachineRate": number;
    "usedSnapshotQuota": number;
    "usedSnapshotRate":string;
    "usedStorageQuota": number;
    "usedStorageRate":string;
    "usedVmQuota": number;
    "usedVmRate":string;
    "vmQuota": number;
    constructor() {
        this.cpuQuota = 0;
        this.dbQuota = 0;
        this.diskQuota = 0;
        this.floatIpQuota = 0;
        this.imageQuota = 0;
        this.memQuota = 0;
        this.networkQuota = 0;
        this.physicalMachineQuota = 0;
        this.snapshotQuota = 0;
        this.storageQuota = 0;
        this.usedCpuQuota = 0;
        this.usedCpuRate = '';
        this.usedDbQuota = 0;
        this.usedDbRate = '';
        this.usedDiskQuota = 0;
        this.usedDiskRate = '';
        this.usedFloatIpQuota = 0;
        this.usedFloatIpRate = '';
        this.usedImageQuota = 0;
        this.usedImageRate = '';
        this.usedMemQuota = 0;
        this.usedMemRate = '';
        this.usedNetworkQuota = 0;
        this.usedNetworkRate = '';
        this.usedPhysicalMachineQuota = 0;
        this.usedPhysicalMachineRate = 0;
        this.usedSnapshotQuota = 0;
        this.usedSnapshotRate = '';
        this.usedStorageQuota = 0;
        this.usedStorageRate = '';
        this.usedVmQuota = 0;
        this.usedVmRate = '';
        this.vmQuota = 0;
    }

}