export const subAccountList_mock = {
"resultCode": "100",
  "detailDescription": null,
  "resultContent": [
    {
      "id": "257876b7-8529-4fb9-ae6e-f0c257e4f026",
      "loginName": "王国庆001",
      "tenantName": "京东方",
      "orgName":"无组织",
      "orgId":"1",
      "status": "2",
      "lastUpdate": "2017-4-12",
      "operator": "某人",
      "description": "不可描述",
      "accessUrl":"https://baidu.com",
      "accessKey": "LTAIs2TkrMZXgPN3",
      "accessSecret":"pX625bPVzXvP3vmu8DcwJ5FubWWXp5",
      " isEditable":"1",//1有 0 没有
    },
    {
      "id": "257876b7-8529-4fb9-ae6e-f0c257e4f027",
      "loginName": "王国庆002",
      "tenantName": "京东方1",
      "orgName":"无纪律",
      "orgId":"2",
      "status": "2",
      "lastUpdate": "2017-4-19",
      "operator": "某人de",
      "description": "可描述",
      "accessUrl":"https://souhu.com",
      "accessKey": "LTAIs2TkrMZXgPN3",
      "accessSecret":"pX625bPVzXvP3vmu8DcwJ5FubWWXp5",
      " isEditable":"1",
    },
    {
      "id": "257876b7-8529-4fb9-ae6e-f0c257e4f028",
      "loginName": "王国庆003",
      "tenantName": "京东方2",
      "orgName":"无法",
      "orgId":"3",
      "status": "1",
      "lastUpdate": "2017-4-12",
      "operator": "某人",
      "description": "不可描述",
      "accessUrl":"https://baidu.com",
      "accessKey": "LTAIs2TkrMZXgPN3",
      "accessSecret":"pX625bPVzXvP3vmu8DcwJ5FubWWXp5",
      " isEditable":"0",
    },
    {
      "id": "257876b7-8529-4fb9-ae6e-f0c257e4f029",
      "loginName": "王国庆004",
      "tenantName": "京东方3",
      "orgName":"",
      "orgId":"4",
      "status": "1",
      "lastUpdate": "2017-4-12",
      "operator": "某人",
      "description": "不可描述",
      "accessUrl":"https://baidu.com",
      "accessKey": "LTAIs2TkrMZXgPN3",
      "accessSecret":"pX625bPVzXvP3vmu8DcwJ5FubWWXp5",
      " isEditable":"0",
    },
  ],
  }
  export const EnterpriseList_mock = {
"resultCode": "100",
  "detailDescription": null,
  "resultContent": [
    {
      "tenantName": "企业1",   
      "tenantId":"1",
      "status": "1",
    },
    {
      "tenantName": "企业2",
      "tenantId":"2",
      "status": "2",
    }
  ]
  }