export const TranslateCN = {
    LANG: '中文',
    SITE: {
        EXIT: '退出'
    },
    DIALOG: {
        PROMPT: '提示',
        CONFIRM: '确认',
        CANCEL: '取消'
    },
    ENT_ADMIN_MNG: {
        ENSURE: '确定',
        CONFIRM: '确认',
        SAVE: '保存',
        CANCEL: '取消',
        RETURN: '返回',

        ENT_ADMIN_SETUP: '企业管理员设置',
        RETURN_TO_ENT_MNG: '返回企业管理列表',
        MORE_OPERATION: '更多操作',
        EDIT: '编辑',
        RESET_PWD: '重置密码',
        ENABLE: '启用',
        DISABLE: '禁用',
        DELETE: '删除',
        CREATE_ADMIN: '创建管理员',
        CHOOSE: '选择',
        ADMIN: '管理员',
        ACCOUNT: '账号',
        PHONE: '联系电话',
        TYPE: '类型',
        ACCOUNT_STATUS: '账号状态',
        DESCRIPTION: '描述',
        CHOOSE_AUTHENTICATION: '认证源选择',
        CREATE: '创建',
        AUTHENTICATION: '认证源',

        CREATE_EDIT_ENT_ADMIN: '创建/编辑企业管理员',
        ENTERPRISE: '企业',
        ADMIN_NAME: '管理员姓名',
        UPDATE_ADMIN: '更新管理员',
        ADD_ADMIN: '新增管理员',

        CREATE_AD_USER: '创建AD用户',
        NAME: '姓名',
        PLEASE_INPUT_NAME: '请输入姓名',
        PLEASE_INPUT_ADMIN_NAME: '请输入管理员姓名',
        PLEASE_INPUT_ADMIN_ACCOUNT: '请输入管理员账户',
        PLEASE_INPUT_PHONE: '请输入联系电话',
        PLEASE_INPUT_VALID_EMAIL: '请在账号输入合法的邮箱',
        PLEASE_INPUT_VALID_PHONE: '请输入合法的联系电话',
        AD_USER_ACCOUNT: 'AD用户帐号',
        USER_NAME: '用户名',
        EMAIL: '邮箱地址',

        EDIT_AD_USER: '编辑AD用户',
        PLEASE_INPUT_DESCRIPTION: '请输入联系描述',

        CREATE_SUCCESS: '创建成功',
        ACCOUNT_EXISTS: '该账户已经被占用',
        UPDATE_SUCCESS: '更新成功',
        GETTING_DATA_FAILED: '获取数据失败！',
        PROMPT: '提示',
        ALERT: '警告',

        PLEASE_CHOOSE_AUTHENTICATION_QUERY: '请选择认证源并且输入查询字符串',
        PLEASE_CHOOSE_AD_USER: '请选择ad用户',
        PLEASE_CHOOSE_ADMIN_TO_DELETE: '请先选择需要删除的管理员！',
        CONFIRM_DELETE_ADMIN: '确认删除{{admin}}?',
        PLEASE_CHOOSE_ADMIN_TO_DO: '请先选择需要{{operation}}的管理员！',
        ADMIN_ALREADY_STATUS: '该管理员已经是${x}状态！',
        PLEASE_CHOOSE_ADMIN_TO_EDIT: '请先选择需要编辑的管理员！',
        PLEASE_CHOOSE_ADMIN_TO_PWD_RESET: '请先选择需要重置密码的管理员！',
        PWD_RESET_SUCCESS: '密码重置成功',
        LOCAL: '本地',
    }
}