export const TranslateCN = {
    LANG: '中文',
    SITE: {
        EXIT: '退出'
    },
    DIALOG: {
        PROMPT: '提示',
        CONFIRM: '确认',
        CANCEL: '取消'
    },
    MENU: {
        CLOUD_HOSTING_SERVICES: '云主机服务',
        CLOUD_HOSTING_INSTANCE: '云主机实例',
        CLOUD_HARD_DISK: '云硬盘',
        VIRTUAL_MACHINE_INSTANCE: '虚拟机实例',
        MIRROR: '镜像',
        PHYSICAL_SERVERS: '物理机服务',
        ACCOUNT_MANAGEMENT: '账号管理',
        EXPENSE_CENTER: '费用中心',
        LOAD_BALANCER: '负载均衡服务器',
        DEPARTMENT_MANAGENMENT: '部门管理',
        AUTHORITY_MANAGEMENT: '权限管理',
        PRICE_SET: '价格设置',
        QUOTA_MANAGEMENT: '配额管理',
        APPROVAL_CENTER: '审批中心',
        NOT_APPROVED: '未审批',
        APPROVED: '已审批',
        PURCHASED_SERVICE_MANAGEMENT: '已购服务管理',
        ORDER_INQUIRY: '订单查询',
        ACCOUNT_CENTER: '用户中心',
        ORGANIZATION_MANAGENMENT: '组织管理',
        PERSONAL_ACCOUNT_MANAGEMENT: '个人账户管理',
        PRODUCTS_SERVICES: '产品与服务',
        CLOUD_HOSTING: '云主机',
        OVERVIEW: '概览',
        ORDER: '订购',
        INSTANCE_LIST: '实例列表'
    },
    NET_MNG_VM_IP_MNG: {
        COMFIRM: '确认',
        CNACLE: '取消',
        RETURN: '返回上一级',
        SELECT_OPERATION: '选择操作',

        FREE: '空闲',
        OCCUPIED: '已占用',
        ALL: '所有',

        OCCUPY: '占用',
        RELEASE: '释放',

        NETWORK: '网络',
        NET_MNG: '网络管理',
        MANAGE_STD_NET: '管理标准网络',
        MANAGE_DBT_NET: '管理分布式网络',
        MANAGE_NSX_NET: '管理NSX网络',
        IP_ADDRESS_MNG: 'IP地址管理',
        MANAGE_IP_ADDRESS: '管理IP地址',

        
        DC_NAME: '数据中心(DC)名称',
        CLUSTER_NAME: '可用区(集群)名称',
        VDS_NAME: '分布式交换机名称',

        SET_IP_SUBNET: '设置IP子网',
        SET_IP_POOL: '设置IP地址范围',

        SELECT: '选择',

        DC: '数据中心(DC)',
        PORTGROUP_NAME: '标准端口组名称',
        PORTGROUP_DISPLAY_NAME: '标准端口组显示名称',
        VDS_PORTGROUP_NAME: '分布式虚拟端口组名称',
        VDS_PORTGROUP_DISPLAY_NAME: '分布式端口组显示名称',
        VLAN_ID: 'VLAN ID',
        SUBNET_INFORMATION: '子网信息',
        GATEWAY_ADDRESS: '网关地址',
        IP_NUMBER: 'IP地址池数量',
        USED_IP_NUMBER: '已使用IP地址数量',
        REST_IP_NUMBER: '剩余IP地址数量',

        SUBNET_MASK: '子网掩码',
        GATEWAY: '网关',
        IP_SCOPE: 'IP地址范围',

        IP_ADDRESS: 'IP地址',
        HOST_NAME: '主机名称',
        ENTERPRISE_NAME: '企业名称',
        STATUS: '状态',
        DESCRIPTION: '说明',

        GETTING_DATA_FAILED: '获取数据失败',
        DICTIONARY_FAILED: '数据字典出错',
        PLEASE_CHOOSE_PG: '请选择相应的PortGroup',
        PLEASE_CHOOSE_DC: '请选择相应的dataCenter',
        PLEASE_CHOOSE_ITEM: '请选择相应的行',
        SET_IP_POOL_SUCCESS: '设置IP地址范围成功',
        SET_IP_POOL_FAILED: '设置IP地址范围失败',
        SET_IP_POOL_EXCEPTION: '设置IP地址范围异常',
        SET_SUBNET_SUCCESS: '设置IP子网成功',
        SET_SUBNET_FAILED: '设置IP子网失败',
        SET_SUBNET_EXCEPTION: '设置IP子网异常',
        SYSTEM_PROMPT: '系统提示',
        PROMPT: '提示',
        UNSET: '未设置',
        PLEASE_INPUT_DESCRIPTION: '请填写说明',

        IP_OCCUPIED: 'IP已被占用',
        IP_OCCUPIED_SUCCESS: 'IP占用成功',
        IP_OCCUPIED_FAILED: 'IP占用失败',
        IP_OCCUPIED_EXCEPTION: 'IP占用异常',
        IP_RELEASED: 'IP未被占用, 无法释放',
        IP_RELEASED_SUCCESS: 'IP释放成功',
        IP_RELEASED_FAILED: 'IP释放失败',
        IP_RELEASED_EXCEPTION: 'IP释放异常',
    }
}